### ISSUE TITLE
CSS for changing the font

### ISSUE THREAD

**Issue by tsenegas** [rstudio/distill#100]
Hi,

is it possible for you to share the source css code? That will allow me to change the font and comply with the graphic chart of my organization.

Thanks for your help and thanks a lot for this awesome way to create a blog/website so easily.

**Comment by jjallaire** [comment]
You can use the `css` YAML option (as documented here: https://www.rdocumentation.org/packages/distill/versions/0.7/topics/distill_article) to include your own CSS file.

A word of warning though: Distill (the original library upon which the R package is based) is strongly opinionated about CSS and sometimes it's tricky or impossible to change things. Just to say your mileage may vary and if there is something you can't quite get right there is not likely much we can do about it.

**Comment by apreshill** [comment]
@tsenegas We now have a theming system and docs about how to change your font ✨ 

https://rstudio.github.io/distill/website.html#theming
