### ISSUE TITLE
Cannot include bibliography ('pandoc-citeproc' not found?)

### ISSUE THREAD

**Issue by maraab23** [rstudio/distill#103]
Every time I try to add a bibliography to my .Rmd-file I get the error message:

```
Error in system(command, intern = TRUE) : 'pandoc-citeproc' not found
Calls: <Anonymous> ... pandoc_citeproc_convert -> with_pandoc_safe_environment -> force -> system
Execution halted
```

My YAML looks like this:
```
---
title: "Distill for R Markdown"
description: | 
  Trying to add bibliography
bibliography: biblio.bib
output: distill::distill_article
---
```

Everything works fine until I add `bibliography: biblio.bib`. 
Actually I am surprised by the error because after having read #45 I thought that distill is not using pandoc-citeproc.

**Comment by cderv** [comment]
There is a question on this in community.rstudio.com
https://community.rstudio.com/t/distill-references-do-not-work/40544

In the code,we see that `pandoc_citeproc` is used 
https://github.com/rstudio/distill/blob/806955bd98bcb2589df77ef99574b58984a6aa3a/R/metadata.R#L472-L475

I can reproduce on windows. Can you confirm if you are on windows or not ? 

I think this is an issue on windows only in rmarkdown with `pandoc_citeproc()` as `pandoc-citeproc` does not exists but `pandoc-citeproc.exe`  does exist.

**Comment by maraab23** [comment]
> I can reproduce on windows. Can you confirm if you are on windows or not ?
> 
> I think this is an issue on windows only in rmarkdown with `pandoc_citeproc()` as `pandoc-citeproc` does not exists but `pandoc-citeproc.exe` does exist.

Yes, I am on windows. Thanks for looking into this issue. Now, let's hope someone comes up with a solution :wink:
