### ISSUE TITLE
Error in if (tz != "UTC")  { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by carloscinelli** [rstudio/distill#104]
When creating a simple distill article (as below), if `tz` is `NA`, knitr throws an error:

> Error in if (tz != "UTC")  { : missing value where TRUE/FALSE needed

Example distill article:

```
---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

```

**Comment by jjallaire** [comment]
That particular code isn't from within distill. Maybe something in knitr or rmarkdown -- @yihui  ?

**Comment by carloscinelli** [comment]
> That particular code isn't from within distill. Maybe something in knitr or rmarkdown -- @yihui ?

The problem happens when setting the Rmarkdown output to `output: distill::distill_article` though. When outputting pdf or vanilla html, it knits correctly even when `tz`  is `NA`.

**Comment by jjallaire** [comment]
Right, Distill might be triggering a codepath that normal documents don't.

**Comment by yihui** [comment]
Could you call `rmarkdown::render()` on the document in the R console and print `traceback()` to see where the error came from? The culprit might be one of these two functions: https://github.com/rstudio/distill/blob/806955bd98bcb2589df77ef99574b58984a6aa3a/R/utils.R#L97-L111

**Comment by jjallaire** [comment]
I searched the knitr and rmarkdown source code and didn't find that code snippet. +1 on a stack trace being essential to sort this out.

**Comment by carloscinelli** [comment]
14: .strptime(x, formats[[1]], tz = tz, quiet = quiet, locale = locale)
13: .parse_date_time(x, formats, tz = tz, quiet = quiet, locale = locale)
12: .local_parse(x[to_parse], TRUE)
11: parse_date_time(dates, orders, quiet = quiet, tz = tz, locale = locale, 
        truncated = truncated)
10: .parse_xxx(..., orders = "ymd", quiet = quiet, tz = tz, locale = locale, 
        truncated = truncated)
9: lubridate::ymd(date, tz = Sys.timezone(), quiet = TRUE)
8: parse_date(date)
7: resolve_date(article_dir, metadata$date)
6: transform_metadata(file, site_config, collection_config, metadata, 
       auto_preview)
5: transform_configuration(file = output_file, site_config = site_config, 
       collection_config = NULL, metadata = metadata, auto_preview = !self_contained)
4: overlay(...)
3: output_format$post_knit(yaml_front_matter, knit_input, runtime, 
       encoding = encoding)
2: call_post_knit_handler()
1: rmarkdown::render(input = "test_site/Untitled.Rmd")

**Comment by carloscinelli** [comment]
Apparently the culprit is 

`lubridate::ymd(date, tz = Sys.timezone(), quiet = TRUE)`

Maybe you want to check whether `Sys.timezone()` is `NA` before feeding it to lubridate?

**Comment by carloscinelli** [comment]
I guess `lubridate::ymd` should handle `NA`s better as well, will open an issue there.

**Comment by jjallaire** [comment]
Fixed here:
https://github.com/rstudio/distill/commit/596111ec516232d06f35d2af35bb371c75ad55a2

**Comment by carloscinelli** [comment]
It is working correctly thus far, thanks @jjallaire
