### ISSUE TITLE
Feature request: Lightbox for gutter plots and images

### ISSUE THREAD

**Issue by howardm** [rstudio/distill#105]
Hi,

I'm not a coder but would really appreciate a lightbox function for images I place in the gutter via the `<aside>` function. I'm a radiologist and wish to explore Distill for creating a teaching website in which images are central.

The requisite function is present , for example, in the [tuftesque2](http://nickstrayer.me/tuftesque2/) theme for a .Rmd document.

Sincerely,

Howard

**Comment by hwoodiwiss** [comment]
Hi,

It would be useful for a maintainer of the project to comment on this, but, from previous similar requests, I don't think it's super likely to be accepted (See #61).

I've been looking into an alternate way to solve this for you.

If you surround each item in the <aside> that you want to be light-boxed with div tags with the class lightbox, like so:
```HTML
<div class="lightbox"> 
{Your R Markdown} 
</div>
```
and add these code blocks to the bottom of your .rmd

````js
```{js}
$(document).ready(function () {
    $('.lightbox').each(function () {
        $(this).click(function (e) {
            var classes = $(this).attr('class').split(/\s+/);
            if(classes.includes('open'))
            {
                $(this).removeClass('open');
            }
            else
            {
                $(this).addClass('open');
            }
        });
    });
});
```
````
````css
```{css}
.lightbox.open {
  position: fixed;
  z-index: 500;
  width: 100%;
  height: 100%;
  text-align: center;
  top: 0;
  left: 0;
  transition: background 300ms ease-in-out;
  background: rgba(0, 0, 0, 0.8);
}

.lightbox.open img {
  margin: auto;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: auto;
  max-width: 95%;
  height: auto;
  max-height: 90%;
}

d-article {
  contain: unset !important;
}
```
````

You should end up with the desired result.

**Comment by hwoodiwiss** [comment]
Better yet, if you include these two files at the root of your distill project:
[lightbox.zip](https://github.com/rstudio/distill/files/3726451/lightbox.zip)

You can have the same effect, by just including this line at the bottom of your .Rmd file:

```html
<script type="text/javascript" src="lightbox.js"></script>
```

The script deals with including the css, and you'll just need to wrap the images you want in a <div> with the lightbox class.

**Comment by howardm** [comment]
Thanks. The "full" script works nicely! I haven't tried the above just yet because I'm working with a single, standalone file at present (website to come later).

I really like the way one can click to get the lightbox, and click again to dismiss it.

I changed one line to: 
`background: rgba(0, 0, 0, 1.0);`

to get a completely black background.

**Comment by hwoodiwiss** [comment]
I'm glad this works for you. I would definitely recommend trying the second method once you start to span across multiple files, as I would imagine it will ease integration, and improve maintainability.

Feel free to play with the css to best suit your needs, in the combined solution, it's all in the lightbox.css file.

**Comment by hwoodiwiss** [comment]
Hope this adequately solves this for you! :)

If so, would you mind closing this issue.

If not, please explain what other requirements you would like this to meet.
