### ISSUE TITLE
Leaflet markers do not show up with layout="l-screen-inset"

### ISSUE THREAD

**Issue by AndersFenger** [rstudio/distill#106]
When knitting a `distill::distill_article` with the following code in a chunk with chunk option `layout="l-screen-inset"` (or any other non-default `layout` argument) added markers are not seen on the map.

``` r
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```

The code is taken directly from the documentation <https://rstudio.github.io/distill/figures.html#full-screen-layout>. Note that the issue can already be observed from this documentation page where the marker of the birthplace of R is not seen.

**Comment by jarrodscott** [comment]
Any solution to this issue? I am encountering the same problem. Thanks!

**Comment by jarrodscott** [comment]
@AndersFenger 
For what its worth I was able to get `layout='l-screen-inset` to work with `addCircleMarkers` instead of `addMarkers`.

```
leaflet() %>%
  addTiles() %>% 
  addCircleMarkers(lng = c(-82.334720, -82.131119), 
             lat = c(9.219640, 9.248433), radius = 25,
             popup = c("Cayo Roldan (impacted)", "Coral Caye (control)"),
             color = c("#141414", "#141414"), 
             fillColor = c("#D55E00", "#0072B2"), 
             stroke = TRUE, fillOpacity = 0.9, weight = 10)
```

**Comment by rbcavanaugh** [comment]
Any chance there's an update on this? Would love to have full screen leaflet maps with markers.

**Comment by cderv** [comment]
It took me a while to find what was happening. I think I found what was the problem. This should now be fixed in dev version of **distill**

Thanks a lot for your patience on this.

**Comment by rbcavanaugh** [comment]
thank you!!
