### ISSUE TITLE
Is it possible to mask a post?

### ISSUE THREAD

**Issue by p0bs** [rstudio/distill#109]
First things first: many thanks for this wonderful tool.

I'm currently using distill for my site but have a couple of posts that I'd like to be retrievable for people with the URL that I wouldn't want to appear on the homepage.

In other words, it is not a draft post; rather, a post that I wouldn't want in general circulation. (And 'security by obscurity' is good enough for me, even if the site is crawled by search engines.)

Is there a way to achieve this functionality in distill? For example, could it be a third option for `draft` (like `draft: masked`)?

Many thanks again.

**Comment by p0bs** [comment]
This is a great solution.

Before, with `draft: true`, the post didn't appear in any way. Not on the home page (as required), not via RSS (as required), not via the categories (as required) and not as a standalone link (which I wanted to change).

Having now removed `draft: true` and altered *index.Rmd* as you suggested, the post appears as I wish. That is, not on the home page (as required), not via RSS (as required), not via the categories (as required) but as a standalone link (as required).

Many thanks again.

**Comment by jjallaire** [comment]
Great, glad things are working as you had hoped!
