### ISSUE TITLE
Increasing page width when embedding a shiny app using iframe in a Distill post

### ISSUE THREAD

**Issue by czopluoglu** [rstudio/distill#119]
Is it possible to increase (or override) the page width in the current theme? I am particularly asking for future posts I would like to embed a shiny app using iframe. Right now, it is looking odd.

[The original shiny app](https://cengiz-zopluoglu.shinyapps.io/names/)

[Same shiny app on the website](https://cengiz.me/posts/shinyapp/)

Is it possible to override the default page width so it extends the embedded shiny app with the figure next to the sidebar as in the original app (not at the bottom)?

I know you can do this for figures created within the R chunks, but not sure how it would work for a shiny app embedded using iframe.

Anyone has any idea if there is a workaround?

Thank you.

**Comment by jjallaire** [comment]
You just need to add one of the figure layout classes to the iframe (e.g. `l-screen-inset`). Various layout options are described here: https://rstudio.github.io/distill/figures.html#

**Comment by czopluoglu** [comment]
Thank you. Could you please write it explicitly?

The previous version was 

<iframe src="https://cengiz-zopluoglu.shinyapps.io/names/" width="100%" height="100%"></iframe>

How should I incorporate your suggestion? I tried this but it didn't work.

<iframe src="https://cengiz-zopluoglu.shinyapps.io/names/" layout="l-screen-inset shaded"></iframe>

**Comment by jjallaire** [comment]
Try class= rather than layout=, for example:

```html
<iframe src="https://cengiz-zopluoglu.shinyapps.io/names/" class="l-screen-inset shaded"></iframe>
```

**Comment by czopluoglu** [comment]
This worked perfectly. Thank you so much for your help!

<iframe src="https://cengiz-zopluoglu.shinyapps.io/names/" class="l-screen-inset shaded" height="1000px"></iframe>

**Comment by valentinaandrade** [comment]
Hi 😄 
This don't work for me
`<iframe src="https://cengiz-zopluoglu.shinyapps.io/names/" class="l-screen-inset shaded" height="1000px"></iframe> `
I use

`<iframe scrolling="no" frameborder="no" src="https://cengiz-zopluoglu.shinyapps.io/names/" class="l-screen-inset shaded" style="width:1000px;height: 100vh;"></iframe>
`
