### ISSUE TITLE
add_metadata (...) thesis not found

### ISSUE THREAD

**Issue by henry090** [rstudio/distill#121]
Hi @ jjallaire, yesterday I was migrating from radix to distill website but encountered an error.
Dev version of distill caused an issue while rendering a post: "in add_metadata not found a thesis". I ended up installing the version from CRAN, and it worked.

**Comment by jooyoungseo** [comment]
@henry090, my latest PR has broken this, and I will patch this soon.

Until then, please keep using stable CRAN version.

Sorry for any inconvenience.
