### ISSUE TITLE
[Question] Way to remove /posts/ directory from rendered Distill blog?

### ISSUE THREAD

**Issue by chrisrmiller** [rstudio/distill#135]
I'm creating a new Distill blog and would like for `/posts/` to not appear in the URL. Is there an easy way to achieve this? I don't mind forking the Distill repo if necessary.

In other words, I would like post URLs to appear as follows: `https://my-distill-blog.com/my-slug`

I realize that posts are initially created within the `_posts` directory, and upon building are copied to the `_site/posts/` directory, which makes total sense. I'm just wondering if there's an easy way to modify this behavior?

I've poked around in the source file `distill/R/create.R`, and it looks like the behavior I'm describing goes even deeper into perhaps `rmarkdown::render()` territory but I'm getting a bit lost.

Thanks!

**Comment by jjallaire** [comment]
I wouldn't try to fight this as the notion of URLs in named collections is baked into many places. I'm sure you could do it, but you'd end up with a lot of head scratching and a fork which you'd have to keep maintaining over time.

**Comment by chrisrmiller** [comment]
Thank you J.J. I was afraid of that. Glad to hear it from someone who knows
better, before I wasted lots of time fiddling with it.

Chris
