### ISSUE TITLE
In the docs website, make it clearer how to choose between website and blog?

### ISSUE THREAD

**Issue by maelle** [rstudio/distill#138]
I.e. maybe add a paragraph at the beginning of "creating a website" and "creating a blog" explaining what the difference is between the two creation processes in practice, and what difference you make between the two types of websites? I am assuming the difference is on "dating content".

**Comment by jjallaire** [comment]
Yes, websites are just collections of pages you can navigate to via the menu, whereas blogs have collections of posts that can be indexed and syndicated. Another important difference is that blog articles are not re-rendered when the site is rebuilt (that way you don't need to reconstruct all of the R dependencies for every post in your blog every time you rebuilt the site, something which in practice is impossible to do for any non-trivial set of articles written over a period of time).

Would again be happy for a contribution to the docs via PR if you are so motivated!

**Comment by maelle** [comment]
Thanks, that's much clearer for me now and yes, I'll make PRs this week or next!

**Comment by jjallaire** [comment]
Thanks, very much appreciated!!!!
