### ISSUE TITLE
RSS feed creation should be independent from locale

### ISSUE THREAD

**Issue by maelle** [rstudio/distill#140]
I've just tried [validating](https://validator.w3.org/feed/) the [RSS feed](https://maelle-distill-test.netlify.app/index.xml) of my [test website](https://github.com/maelle/maelle-distill) and it didn't go well because of the dates in French.

I'm not sure how this should be fixed. 

``` r

date <- as.Date("2020-06-03")
distill:::date_as_rfc_2822(date)
#> [1] "mer., 03 juin 2020 00:00:00 +0000"

withr::with_locale(
  new = c("LC_TIME" = "en_US.UTF-8"),
  distill:::date_as_rfc_2822(date)
)
#> [1] "Wed, 03 Jun 2020 00:00:00 +0000"
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maelle** [comment]
I also can't get a full content feed but that's a separate issue (since it is still the case after I change the locale). #99

**Comment by maelle** [comment]
I'd be happy to make a PR to fix this, but would it be ok to add a withr dependency?

**Comment by jjallaire** [comment]
withr dependency is fine.

If you could give us the PR soon it would be great (as we are just about to submit a new release to CRAN).

**Comment by maelle** [comment]
:running_woman: to my fork now then!
