### ISSUE TITLE
Weird formatting after code blocks

### ISSUE THREAD

**Issue by michiexile** [rstudio/distill#150]
As can be seen on http://michiexile.rbind.io/posts/2020-07-24-bootstrap/ - text gets formatted into a very narrow right hand column after figures and code blocks.

The source is available here: https://github.com/michiexile/rbind-io/blob/master/_posts/2020-07-24-bootstrap/bootstrap.Rmd

**Comment by jbkunst** [comment]
Hi @michiexile 

Try to add space before the r chunk. 

Not sure if this is a bug, but I think always is good have space :) in the code to be more readable.

![image](https://user-images.githubusercontent.com/56481/88448224-6f90a780-ce09-11ea-89fc-cdffec441a05.png)

![image](https://user-images.githubusercontent.com/56481/88448236-8cc57600-ce09-11ea-9904-ab69e96760b0.png)

If this is solved don't forget to close the issue.

Hope it helps.

**Comment by jjallaire** [comment]
Yes, markdown actually requires the space to properly delineate the blocks (and has this sort of requirement in other places as well so generally a very good principle to use spaces).
