### ISSUE TITLE
Adding banner image to single page

### ISSUE THREAD

**Issue by jarrodscott** [rstudio/distill#153]
Hi!

Is it possible to add a full width banner style image to a single page (e.g., the `index.Rmd`) that sits above the title/subtitle of the page? I know how to do this with a simple R Markdown website (using `includes: in_header: header.html`) but I cannot figure out how to code it in Distill.

Thanks!

**Comment by jarrodscott** [comment]
Never fails. You can spend a week trying to solve a problem, give up, post the question, and *then* find a solution. In this case, at least a partial solution. Anyway, here is how I did it. Open to suggestions on making the code better...

First I created an html file for the banner image:

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="article-header">
      <img src="assets/banner.png" class="article-banner" alt="">
    </div>
    </a>
  </body>
</html>
```

Then I added this to the custom css file

```
.article-banner {
  width: auto;
  height: auto;
  border: 0;
}

img[src="assets/banner.png"] {
  border: 0;
  padding: 0;
  width: 100%;
  margin: 100px 25px 0px 0px;
}
```

And finally added this to the header of the `Rmd`

```
output:
    distill::distill_article:
      includes:
        in_header: assets/header.html
```

**Comment by apreshill** [comment]
Glad you found the solution, thanks for the follow up! I'll look to add this to the docs in a more conspicuous place.

**Comment by jarrodscott** [comment]
Thanks @apreshill . Here is what it looks like in practice.  Sizing the banner png was a little tricky because of the left vs. right margin. Anyway, I love distill r. What a great package

https://hypocolypse.github.io/
