### ISSUE TITLE
Inline citation doesn't not provide more information on hover

### ISSUE THREAD

**Issue by taraskaduk** [rstudio/distill#154]
In [https://rstudio.github.io/distill/basics.html#citations](https://rstudio.github.io/distill/basics.html#citations), it is stated:

> The citation is presented inline like this: (Xie 2015) (a number that displays more information on hover). If you have an appendix, a bibliography is automatically created and populated in it.

However, the underlined "2015" number, while linking to the "References" section at the bottom of the page, does not display more information on hover.
The hover behavior does work for footnotes, but not for references.

Tested on Firefox, Chrome, and Safari, without any add-ons or blockers.

**Comment by jjallaire** [comment]
Right, I noted in the commit and NEWS entry that we end up losing the hover behavior (as that's tied in to the Distill JavaScript implementation). I'll update the docs accordingly.

**Comment by taraskaduk** [comment]
Thank you! I missed that part: I'm new to the framework and studying the documentation now.

**Comment by taraskaduk** [comment]
@jjallaire, well, actually, I'm confused now. At least in the local knit, the hover behavior persists, and my citation style is footnote (hover-able number **[1]**):

<img width="500" alt="Screen Shot 2020-08-27 at 15 06 21" src="https://user-images.githubusercontent.com/16126183/91484197-e12f9b80-e876-11ea-94b6-0105cb70b4a0.png">

In the [https://rstudio.github.io/distill/basics.html#citations](https://rstudio.github.io/distill/basics.html#citations) page of the Distill site, the reference is parenthetical (**Xie 2015**), and with no hover behavior:

<img width="500" alt="Screen Shot 2020-08-27 at 15 06 50" src="https://user-images.githubusercontent.com/16126183/91484262-f5739880-e876-11ea-8aa3-9cc34e7295ad.png">

**Comment by taraskaduk** [comment]
My apologies, I was on v0.8.

**Comment by awconway** [comment]
Wondering if you could let us know if putting back in the hoverable citation functionality is planned at all? This was one of the features I really loved about the distill package.

**Comment by jjallaire** [comment]
Yes, we do plan on restoring this (hopefully in the next release!)

**Comment by jjallaire** [comment]
Restored hoverable references here: https://github.com/rstudio/distill/commit/3a83b0288d3ddc4ae4977dcfa48e8b713d1d02e6
