### ISSUE TITLE
Including and excluding files from subdirectories doesn't seem to work

### ISSUE THREAD

**Issue by clauswilke** [rstudio/distill#158]
Including and excluding files with `include:` and `exclude:` doesn't seem to work if we're trying to match patterns inside a subdirectory. Example:

```
exclude: ["slides/*.Rmd"]
```

The `.Rmd` files are copied nonetheless. Specific including with `include:` doesn't work either. This seems to be a known issue in RMarkdown: https://github.com/rstudio/rmarkdown/issues/951

**Comment by jjallaire** [comment]
This is as others have mentioned in https://github.com/rstudio/rmarkdown/issues/951 tied up with how R Markdown websites process includes/excludes, which is not something we can change easily without risking a lot of breakage. For now I'd recommend placing Rmds you don't want processed within a top-level directory that starts with a `_` (e.g. `_slides/foo.Rmd`).

**Comment by jjallaire** [comment]
I see that this won't work for your use case, b/c you actually want to copy the .html files from `slides` but not the Rmds. For this I'd recommend some sort of custom workflow where e.g. you keep the Rmds in `_slides` but then write a script that renders them to a `slides` directory. I realize that this is pretty inconvenient but there really isn't an easy way to change the default `include/exclude` beahvior.

**Comment by apreshill** [comment]
We may want to update https://rstudio.github.io/distill/website.html#site-output to reflect this.

**Comment by clauswilke** [comment]
My own solution was to simply write a little script that removes the files I don't want in the built site. Adding something like this to the documentation as an example may be helpful.

```sh
#!/bin/sh

Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
rm -rf ./docs/slides/*.Rmd
rm -rf ./docs/worksheets/*.html
rm -rf ./docs/datasets/*.R
git add ./docs/
```

**Comment by jjallaire** [comment]
Addressed via https://github.com/rstudio/distill/commit/900cf153d0724b91944eface8efb1c0188d3d179
