### ISSUE TITLE
Add pkgdown site

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#166]
@jjallaire can we switch the deployed <https://rstudio.github.io/distill/> site (in `docs`, using GitHub Pages) to Netlify? It is looking like the other pkgdown sites we are adding will be using a GitHub Actions workflow to push to the `gh-pages` branch, and then deploy via GitHub Pages. I requested to add this repo from our internal Netlify account, but not sure where those requests go to. Netlify should allow for adding the custom domain name change once we turn off GitHub Pages (temporarily) in this repository. Thank you!

**Comment by apreshill** [comment]
Related: get package hex sticker, designed by @jamjulie 💟

**Comment by apreshill** [comment]
Hi @jjallaire,

In my fork, I've got the current `docs/` site building with a [GitHub Actions workflow](https://github.com/apreshill/distill/blob/pkgdown/.github/workflows/distilldocs.yaml) and deploying to Netlify: <https://naughty-lamport-451d6f.netlify.app/>

And the pkgdown site build with a [workflow](https://github.com/apreshill/distill/blob/pkgdown/.github/workflows/pkgdown.yaml) and pushed to the `gh-pages` branch to deploy via GitHub Pages: https://apreshill.github.io/distill/ (hex is just a draft, we are iterating).

Can you let me know how you want to handle these two sites and the URLs? I can switch these workflows up so that the docs site stays on GitHub pages so the URL stays the same.

**Comment by jjallaire** [comment]
Yeah, I guess for now let's keep the docs site with the same URL. Is this all eventually moving to rmarkdown.io? (or whatever we come up with)

**Comment by apreshill** [comment]
Will do- and it looks like the repo did get the Netlify permissions added. And yes, I imagine we'll have a lot of redirects to juggle whichever path we choose here!
