### ISSUE TITLE
Publish to Netlify

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#167]
(sorry for more issues @jjallaire!)

I had this one bookmarked because it would be great to support publishing to Netlify using their [CLI](https://docs.netlify.com/cli/get-started/), for users who don't set up their sites using the GitHub continuous integration option.

> Currently only supports publishing to RStudio Connect but the interface is extensible to other targets (e.g. Netlify) via the `method` parameter.

Not sure if this can happen in distill or if it should happen upstream in rmarkdown.

+ https://github.com/rstudio/rmarkdown/commit/4ee96c855a4438a91f6bf3daf06472e8c49d22d1

+ https://github.com/rstudio/distill/blob/master/R/publish.R

**Comment by jjallaire** [comment]
That function we put in to support easy non-Git based deployment ("one button" publish including promoting you for configuration/authorization of the RSC connection).

For Netlify it seems like git-based deployment is preferable (although perhaps that's too high a hurdle for some users?). We document that here: https://rstudio.github.io/distill/publish_website.html#netlify

Another thing to consider is that if the user is sophisticated enough to install and configure the netlify CLI, it's not asking much more for them to call `netlify deploy _site` (i.e. we don't add much value via the R function). If OTOH the R function could download and configure the netlify SDK, etc. then it would certainly be adding value (but then are we hiding too much?).

**Comment by apreshill** [comment]
Got it- let me think more about utility for this (closing for now). The best workflow is definitely Github for sure, but for Distill since there is no way for Netlify to do the build for you, there is no continuous deployment complexity like with Hugo. Other higher payoff deploy upgrades might be to follow up on the issue regarding GH actions to build a distill site, but I'll follow up in those issues. Thanks!
