### ISSUE TITLE
HTML links inserted into code blocks?

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#168]
In my tweaking with an accessibility-friendly syntax highlighter, I noticed that there are empty HTML links inserted before each line in a code block. The docs don't have too many examples of this, but you can see them here:

https://rstudio.github.io/distill/basics.html#code-blocks

<img width="972" alt="Screen Shot 2020-09-19 at 10 57 34 PM" src="https://user-images.githubusercontent.com/12160301/93693259-9139a280-facb-11ea-809a-bfcc54527a3f.png">

I'm not sure if this is expected or not. With a custom highlighting theme, the `aria-hidden=TRUE` attribute is lost and doing an accessibility test results in lots of flags for links with no discernable text:

<img width="1193" alt="Screen Shot 2020-09-19 at 10 58 49 PM" src="https://user-images.githubusercontent.com/12160301/93693295-f8efed80-facb-11ea-895b-e38b51067b4f.png">

I don't see these links in the distill dev version pre-downlit; i.e., <https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/>.

**Comment by jjallaire** [comment]
It looks like pandoc adds empty line number links to it's highlighting output whenever it's using a custom theme. I believe this is resolved by this bit of jquery which we now run before the document appears:

```js
$('code.sourceCode a[aria-hidden="true"]').remove();
```

Commit here: https://github.com/rstudio/distill/commit/a6a92d351aee075ee027f63f340a7a26490e3f59

I was seeing `aria-hidden` on all of these links but you mentioned that you saw it dropped when using a custom theme (in that case this fix wouldn't work b/c I'm explicitly looking for `aria-hidden`). What do you see in the rendered doc when running w/ this fix?

**Comment by apreshill** [comment]
It looks like they are still here, I updated all my installs and put my knitted test Rmd files in a repo so you can see: 

+ Custom theme: https://apreshill.github.io/distill-a11y/test-a11y.html

+ Pygments: https://apreshill.github.io/distill-a11y/test-pygments.html

+ Default syntax highlightere: https://apreshill.github.io/distill-a11y/test-default.html (note that the extra links there DO appear in my CSS code chunk at the bottom)


Repo: https://github.com/apreshill/distill-a11y

**Comment by jjallaire** [comment]
There must be a difference in package versions somewhere because even when running the code in your repo I still can't reproduce the links being there. What is the output of `devtools::session_info()` ?

**Comment by jjallaire** [comment]
In particular I don't see this code in the generated html: https://github.com/rstudio/distill/blob/master/inst/rmarkdown/templates/distill_article/resources/distill.html#L734-L737 (which is the code I added to the main distill template to strip the links). 

I noticed another problem though: the aria-hidden is not on the links in your version (this may be b/c of different pandoc versions). I'll fix my JS to not require the aria-hidden bit.

**Comment by jjallaire** [comment]
fix for the `aria-hidden` thing here: https://github.com/rstudio/distill/commit/08911f7bd920a2f0ae1e96bf2d6848ecc2d8b528

**Comment by apreshill** [comment]
Thanks- I just added a session info at the table at the end, before re-installing the package. It's saying I have the GitHub version associated with commit #3bc330276a151c3839e1d05feaaa4376e05afa0d

**Comment by jjallaire** [comment]
Okay, I think we've almost got it. That version does have the JS that is attempting to remove the links, however it's not working b/c the `aria-hidden` attribute isn't on the `<a>` tags. If you update to this commit (https://github.com/rstudio/distill/commit/08911f7bd920a2f0ae1e96bf2d6848ecc2d8b528), which is the current master, then I believe that things will work as expected 🤞

**Comment by apreshill** [comment]
hot 🐕 - that did it! Thank you.

**Comment by jjallaire** [comment]
Excellent :-) Glad we worked this out!
