### ISSUE TITLE
Add option for accessible syntax highlighting theme

### ISSUE THREAD

**Issue by jjallaire** [rstudio/distill#169]
New custom theme based on work here: https://github.com/ericwbailey/a11y-syntax-highlighting

We'll need to add the theme to the resources directory alongside the existing `rstudio.theme`, then update this function to look for e.g. `highlight == "a11y"` and in that case map the request to the theme file. 

Then should add to the documentation here: https://github.com/ericwbailey/a11y-syntax-highlighting

**Comment by jjallaire** [comment]
Added here: https://github.com/rstudio/distill/commit/0b5839986473ad745f6ec95561af7cd0cb73ac6f

I think the theme looks terrific. Should we make it the default?

**Comment by apreshill** [comment]
Thank you! I'm happy you like it- I cannot believe how easy that was, thanks for the prompt. Open to default or as the other option.

**Comment by jjallaire** [comment]
Made it the default here: https://github.com/rstudio/distill/commit/d74c589a70be368ec8e287d589b348c17f831844
