### ISSUE TITLE
TOC flexibility

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#174]
CRAN TOC placement was on top.

Dev version TOC placement is on the side but thresholded to move to the top with narrower screen widths and on mobile.

Consider making TOC placement flexible so users can select top vs side- maybe per article?

**Comment by apreshill** [comment]
I just realized a possible API for this is to call it `toc_float`?

```
---
output:
  distill::distill_article:
      toc: true
      toc_float: true
---
```

See: https://community.rstudio.com/t/floating-toc-in-distill-webpage/59418

Pros: consistent with rmarkdown HTML output, so users are likely familiar with this YAML key
Cons: doesn't *actually* use bootstrap (which rmarkdown does) so could be potentially misleading

**Comment by jjallaire** [comment]
I like the consistency. There would be three possible values: `auto` (the default), `true`, and `false`.

**Comment by jjallaire** [comment]
Resolved here: https://github.com/rstudio/distill/commit/2b38e631e0b74db912d656a41df1fc195f8aa757

Note that it ended up being `true` or `false` (where `true` really means "auto"). This is b/c if `true` meant always show it on the left then mobile displays would be broken (as there isn't really room to show it on the left when we are at < 1000px wide).
