### ISSUE TITLE
Rename post function

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#175]
To address workflow for updating post metadata after working on a draft post; see:

https://community.rstudio.com/t/distill-blog-posts-workflow/81907

**Comment by jjallaire** [comment]
Implemented here: https://github.com/rstudio/distill/commit/52ce6730f1a441cd62f53b1b318cd8dc056a8679

Docs here: https://rstudio.github.io/distill/blog.html#post-directory-name
