### ISSUE TITLE
surname incorrectly formatting

### ISSUE THREAD

**Issue by mfdf** [rstudio/distill#176]
How do you get the surname
di Folco
to appear as it is spelled, rather then Folco?

For author: name: in YAML header, the conversion to a citation renders the surname incorrectly as Folco.

Can we define firstname and surname ourselves, bypassing the authors_with_first_and_last_names() function?

**Comment by jjallaire** [comment]
This commit (https://github.com/rstudio/distill/commit/b7ef6b13be25f219883cea5a6fac417899421061) should fix the issue, by allowing you to explicitly specify `first_name` and `last_name` within author YAML. LMK if this is does the trick.

**Comment by jjallaire** [comment]
You can install this version with `devtools::install_github("rstudio/distill")`

**Comment by mfdf** [comment]
Worked a treat! Thank you.
```
author:
  - first_name: "Maj-Britt"
    last_name: "di Folco"
```
