### ISSUE TITLE
Why doesn't rename_post_dir() default to the date in the post YAML?

### ISSUE THREAD

**Issue by maelle** [rstudio/distill#180]
:wave: here, I was looking at `rename_post_dir()` (that looks handy!) and was wondering why the default date is the current date as opposed to the date in the post. Or, why doesn't the function also change the date in the post?

**Comment by maelle** [comment]
A related remark: I was looking for the function in the Blog Post Workflow page, but it's only in the Blog page. Might it be useful to have it documented in the two pages?

I think the question in https://community.rstudio.com/t/distill-blog-posts-workflow/81907/3 could also inspire a subsection of the "Blog Post Workflow" that'd explain how to publish a post once you've settled on a date and title.

**Comment by jjallaire** [comment]
Good point! (an oversight). Fixed here: https://github.com/rstudio/distill/commit/a88659523a83b67ac22983993391d266fd45f9db

**Comment by maelle** [comment]
:+1: :pray:
