### ISSUE TITLE
Consider create_article() function

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#187]
that wraps:

```
rmarkdown::draft("article.Rmd", "distill_article", package = "distill", edit = TRUE)
```

See:
https://community.rstudio.com/t/distill-project-skeleton-yml-source-for-metadata/71492

and

https://github.com/rstudio/distill/issues/129

**Comment by jjallaire** [comment]
Resolved via https://github.com/rstudio/distill/commit/a4309786692363341566a63ae22328bb364e23b2
