### ISSUE TITLE
Docs: long header on index page

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#188]
Hi @jjallaire seeing this:

<img width="1262" alt="Screen Shot 2020-10-05 at 5 11 20 PM" src="https://user-images.githubusercontent.com/12160301/95132617-12c93b80-072e-11eb-92e5-e986feeaa37e.png">

Looks like the level 2 header there is wrapped in this- is this intentional?

https://github.com/rstudio/distill/blob/6999f43d6b2df504d0ff8ffdf497e200bf7844f5/docs/_common/distill_basics.Rmd#L1-L3

**Comment by jjallaire** [comment]
Good catch! Fixed.
