### ISSUE TITLE
Can't follow instructions: missing components

### ISSUE THREAD

**Issue by RRemelgado** [rstudio/distill#194]
Hi,

I was following your tutorials in hopes of adding a search box to my website. However, when I use the `search: true` prompt as suggested, it does not create one. I realize the website is missing some java components in sitelib when I build the website.

**Comment by RRemelgado** [comment]
sorry, my bad...I needed to install the package through GitHub instead of CRAN.

**Comment by jjallaire** [comment]
Sorry about that! We hope to have a new CRAN release over the next few days.
