### ISSUE TITLE
Side by side figures not working

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/distill#196]
In bookdown html documents, the chunk options `fig.show='hold'` and `out.width='50%'` enable the display of two (or more) figures from one code chunk side by side. The distill documentation also links to the bookdown book figures chapter (https://bookdown.org/yihui/bookdown/figures.html), but said feature does not work. Instead, all images from the chunk are full width in the output.

**Comment by jjallaire** [comment]
Right, we just support figure cross-references not all of the bookdown figure features.

**Comment by apreshill** [comment]
Hi @jmbuhr -

I believe this goes beyond bookdown. See: 
https://bookdown.org/yihui/rmarkdown-cookbook/figures-side.html

I just tried this and it worked:

```{r, echo=TRUE, figures-side, fig.show="hold", out.width="50%"}
par(mar = c(4, 4, .1, .1))
plot(cars)
plot(mpg ~ hp, data = mtcars, pch = 19)
```

<img width="1287" alt="Screen Shot 2020-10-13 at 9 30 25 PM" src="https://user-images.githubusercontent.com/12160301/95933107-9e307580-0d9b-11eb-86ba-7c92b572dd33.png">

Where I cannot get it to work is within any of the distill custom [figure layouts](https://rstudio.github.io/distill/#figures). Is that what you tried?

Also note that the side-by-side figures get screwed up by `fig.align = CENTER` (this has bitten me a few times!): https://community.rstudio.com/t/how-to-stack-two-images-horizontally-in-r-markdown/18941/11

**Comment by jmbuhr** [comment]
Oh, indeed, I just tried it again and it worked! I previously tried it with the figure layouts, then removed them and still couldn't get it to work. Maybe I had a lingering fig.align in some options that I now removed without thinking about it. Thanks!
