### ISSUE TITLE
running plot_ly inside distill

### ISSUE THREAD

**Issue by tonytrevisan** [rstudio/distill#205]
When I try and run a plotly graph inside a distill R Project I receive an error (see below). I can run the same code outside a distill project with no error. The HTML still successfully renders, but I am not sure if the error is causing any downstream issues.

This is the code i run within a distill project with the error shown after
```{r plot1}
library(plotly)
p <- plot_ly(economics, x = ~date, y = ~unemploy / pop, type = 'scatter',mode='lines')
p
```

![image](https://user-images.githubusercontent.com/45466366/97089033-f6207500-1602-11eb-9218-9776e2d0a28e.png)

**Comment by jjallaire** [comment]
I'm not able to repro that error w/ distill and plotly from CRAN. Here is my `devtools::session_info()` output so you can compare w/ your config:

```
─ Session info ─────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.5      
 system   x86_64, darwin17.0          
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-10-24                  

─ Packages ─────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 backports     1.1.10  2020-09-15 [1] CRAN (R 4.0.2)
 callr         3.4.4   2020-09-07 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 4.0.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 crosstalk     1.1.0.1 2020-03-13 [1] CRAN (R 4.0.2)
 data.table    1.13.2  2020-10-19 [1] CRAN (R 4.0.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
 digest        0.6.26  2020-10-17 [1] CRAN (R 4.0.2)
 distill       1.0     2020-10-22 [1] CRAN (R 4.0.2)
 downlit       0.2.0   2020-09-25 [1] CRAN (R 4.0.2)
 dplyr         1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.1)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.2)
 ggplot2     * 3.3.2   2020-06-19 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
 htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
 htmlwidgets   1.5.1   2019-10-08 [1] CRAN (R 4.0.2)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
 jsonlite      1.7.1   2020-09-07 [1] CRAN (R 4.0.2)
 knitr         1.30    2020-09-22 [1] CRAN (R 4.0.2)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 4.0.2)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.2)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
 pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.2)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
 plotly      * 4.9.2.1 2020-04-04 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
 ps            1.3.4   2020-08-11 [1] CRAN (R 4.0.2)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 rlang         0.4.8   2020-10-08 [1] CRAN (R 4.0.2)
 rmarkdown     2.5     2020-10-21 [1] CRAN (R 4.0.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.2)
 tibble        3.0.3   2020-07-10 [1] CRAN (R 4.0.2)
 tidyr         1.1.2   2020-08-27 [1] CRAN (R 4.0.2)
 tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
 usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.2)
 vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.2)
 viridisLite   0.3.0   2018-02-01 [1] CRAN (R 4.0.1)
 withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xfun          0.18    2020-09-29 [1] CRAN (R 4.0.2)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
```

**Comment by tonytrevisan** [comment]
Btw... I forgot to mention, I LOVE the distill package, it's really great to use. 
I am actually getting the exact same error running three different OS and three different versions of R:

![image](https://user-images.githubusercontent.com/45466366/97095205-8d4cf300-162a-11eb-8726-7788153e5b4f.png)

![image](https://user-images.githubusercontent.com/45466366/97095208-96d65b00-162a-11eb-9a99-504284af040f.png)

![image](https://user-images.githubusercontent.com/45466366/97095370-71e2e780-162c-11eb-9d61-a314c326310b.png)


Here is the error message from windows. It renders just like it does for linux, so not sure how critical. It is just odd the error doesn't occur running outside of distill.

![image](https://user-images.githubusercontent.com/45466366/97095388-a9ea2a80-162c-11eb-9440-662a7aca2e60.png)

**Comment by jjallaire** [comment]
Could you run the session_info from inside an R Markdown document that
exhibits the error (so I can see all the package versions affecting the
render -- e.g. in at least one of those above I don't see dplyr at all)

**Comment by jjallaire** [comment]
@cpsievert Are you aware of anything in plotly that would trigger this error?

@tonytrevisan It's super-unlikely that this has anything to do with distill per-se, more likely just the combination of package versions loaded when you are rendering this document.

**Comment by tonytrevisan** [comment]
I agree that this is unlikely to do with ‘distill’ because I am having a similar issue with pkgdown (https://github.com/r-lib/pkgdown/issues/1423). I find it odd that I can recreate on multiple OS and multiple R versions but perhaps it’s best to close this issue until I can narrow down the bug on my side and then I can reopen.

**Comment by cpsievert** [comment]
I haven't seen this error before, but I maybe upgrading to the development version of plotly will fix it? `remotes::install_github("ropensci/plotly")`

**Comment by tonytrevisan** [comment]
That does appear to have removed all the warnings and errors. Thank you @cpsievert
