### ISSUE TITLE
ORCID information in metadata

### ISSUE THREAD

**Issue by chris-prener** [rstudio/distill#21]
Starting to play with radix and it is really phenomenal! Is there a way to embed author ORCID information in the metadata? If not, would love to see that as an enhancement...

**Comment by jjallaire** [comment]
WE don't yet support ORCID but agreed that this is a very worthwhile enhancement.

**Comment by chris-prener** [comment]
Thanks for the quick response @jjallaire - will keep my eyes out for a future update!

**Comment by Opussci** [comment]
Is ORCID supported at this moment?

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/distill/commit/537e136578bbc9d88bed69323fe095b1136a4f23
