### ISSUE TITLE
Nav text falls below nav bar when resizing window

### ISSUE THREAD

**Issue by jarrodscott** [rstudio/distill#210]
Hi, 

I am noticing some odd behavior with the nav bar bar when there are too many items and I resize the window. Basically, when you resize the window of say the [distill r homepage](https://rstudio.github.io/distill/), at a certain window width, the nav bar transitions from text to the three bar dropdown menu.  If however you add a few more nav bar items and then begin resizing the window, the text falls below the nav bar before the little three bar dropdown menu appears. I am sorry I cannot offer a solution at this time but if I find one I will add it to this thread. 

I have a fresh install of distillr. To reproduce. 
1) Create new distill website in RStudio
2) Check that `index.html` works when resizing.
3) Add  nav bar items to `_site.yml` file.
4) run `rmarkdown::render_site()` to render

Here is the site on full screen. My screen is 13"
<img width="1431" alt="Screen Shot 2020-10-31 at 9 34 30 AM" src="https://user-images.githubusercontent.com/16192182/97782583-5877f900-1b60-11eb-84d3-98a9f26c9253.png">

Here it is resized. Text is gone but there is no three bar dropdown yet.

<img width="824" alt="Screen Shot 2020-10-31 at 9 35 13 AM" src="https://user-images.githubusercontent.com/16192182/97782600-6c235f80-1b60-11eb-9acb-8ced6d956c04.png">

Here is the same shot with custom css that changes the nav bar text color so you can see the text is now below the nav bar. 

<img width="794" alt="Screen Shot 2020-10-31 at 9 40 38 AM" src="https://user-images.githubusercontent.com/16192182/97782615-89f0c480-1b60-11eb-982b-3bd5547586c9.png">

**Comment by jjallaire** [comment]
Our responsive layout for the navbar isn't quite as capable as e.g. bootstraps (which can handle just about any overflow correctly). For distill you just need to limit the number of top-level nav buttons and use nav menus as required (https://rstudio.github.io/distill/website.html#site-navigation)
