### ISSUE TITLE
navbar display is a little too sensitive

### ISSUE THREAD

**Issue by kevinushey** [rstudio/distill#211]
I noticed on occasion while scrolling through the page at https://rstudio.github.io/distill/:

- I would initiate a two-finger scroll (via macOS trackpad) to scroll down the page;
- After I finished scrolling a bit, the page would scroll back up a single pixel,
- That single-pixel scroll would be enough to trigger the navbar to scroll into view.

Empirically, I can reproduce this fairly reliably if I try to scroll and then stop scrolling quickly. Not sure if this can be patched in our package or if this is worth filing upstream.

Screencast of behavior follows:

---

![distill](https://user-images.githubusercontent.com/1976582/97833237-d08e0e00-1c89-11eb-866b-8b284d554bb1.gif)

**Comment by jjallaire** [comment]
The navbar behavior comes from headroom.js: https://wicky.nillia.ms/headroom.js/

I think we are likely stuck w/ whatever their trackpad behavior/bugs are. If we see something truly egregious we should report upstream but this seems edge case enough to not warrant that.

**Comment by kevinushey** [comment]
FWIW looks like this can actually be configured via the `tolerance` option passed to the Headroom constructor.

I originally thought this also affected packages using `distill` but if it's just `distill`'s own documentation then agree not a big issue.

**Comment by jjallaire** [comment]
Hadn't seen that! Made the change to 5px here:
https://github.com/rstudio/distill/commit/03aa1088ed9a0a856f30f00cecb80f419d1b5c05
