### ISSUE TITLE
Could create_theme() print a TODO list?

### ISSUE THREAD

**Issue by maelle** [rstudio/distill#225]
At the moment if I run `create_theme()` it creates and opens the CSS file which is great. :pray: 

I was wondering whether it could also print things to screen à la usethis:

```r
distill::create_theme()
v Created CSS file at theme.css
o Amend it to suit your needs!
o Apply it by adding its path to your site or article YAML (see https://rstudio.github.io/distill/website.html#apply-theme)

```

**Comment by jjallaire** [comment]
Good idea!

Maybe that last link could wrap onto another line (for small to medium sized screen widths).

Would you give us a PR for this?
