### ISSUE TITLE
Collapsible section code in .Rmd document in Distill

### ISSUE THREAD

**Issue by howardm** [rstudio/distill#234]
Hi,

How do I get a Collapsible Section (reveal and hide Section content by clicking on "plus"sign) in a Distill page as shown in the screenshot below ?
___

![CollapsibleSection](https://user-images.githubusercontent.com/6101226/101584336-aa4f4280-399a-11eb-8928-880ea6a22e23.jpg)

___

Thanks,

Howard

**Comment by maxdrohde** [comment]
I have had success using the `detail` HTML element.

Example:
<details>
    <summary>OTHER EXAMPLES</summary>
    Here are some other examples.
</details

Code:
```
<details>
    <summary>OTHER EXAMPLES</summary>
    Here are some other examples.
</details
```

See this for reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by howardm** [comment]
@maxdrohde 

Thanks.

I recently discovered the use of a Panelset, using xaringanExtra, which suits me even better:

https://pkg.garrickadenbuie.com/xaringanExtra/#/panelset

Howard
