### ISSUE TITLE
Is there a way to include mathjax only when the page/article uses latex?

### ISSUE THREAD

**Issue by chezui** [rstudio/distill#239]
This will greatly improve the site load time.

In Hugo this can be done by adding a flag in the preamble like "math: true" will include the mathjax JS to the header:

https://eankeen.github.io/blog/posts/render-latex-with-katex-in-hugo-blog/

I can also try to implement this if I get some pointers on where to start :)

**Comment by jjallaire** [comment]
This should already be happening as per the pandoc template (the `$if(math)$` should be firing only if there is math in the document):

https://github.com/rstudio/distill/blob/master/inst/rmarkdown/templates/distill_article/resources/default.html#L92-L104

When I render a distill article w/o math I do not in fact see the mathjax JS included. Let me know if you see something different.
