### ISSUE TITLE
Description incorrectly rendered in feed, correct in post

### ISSUE THREAD

**Issue by julianbarg** [rstudio/distill#243]
In the post, a link is rendered correctly. In the feed, a link in the YAML description tag is not rendered correctly and instead, is displayed in plaintext.

Reproducible example:
```---
title: Link test
description:  [Google](https://www.google.com/). 
author:
  - name: name
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---

post: https://www.jbarg.net/posts/2020-12-08-covid-logistics/
feed: https://www.jbarg.net/
Rmd: https://github.com/julianbarg/jules_net/blob/main/_posts/2020-12-08-covid-logistics/covid-logistics.Rmd

**Comment by jjallaire** [comment]
That's unfortunately a known limitation. I'll try to address this is in the next release.

**Comment by jjallaire** [comment]
Unfortunately had to revert this change, see https://github.com/rstudio/distill/commit/6dfc29d4bd771d3fe65be19a2de0ebc396a15fe3
