### ISSUE TITLE
How to handle img in search when there is no image in the post? 

### ISSUE THREAD

**Issue by dcaud** [rstudio/distill#244]
In the search suggestions, I have a bunch of missing img icons...in part because there are no images in the posts. How can I  make the search not show the missing img icons?

Something related to:

                  <img src="${suggestion.preview ? offsetURL(suggestion.preview) : ''}"</img>

**Comment by dcaud** [comment]
An example of what I'm seeing is in one of the demo sites:

https://www.opensourcefootball.com/posts/2020-08-28-expected-completion-using-logistic-generalized-additive-mixed-models/

Type "Python" in the search box and you will see that the first result has a broken img icon.

**Comment by jjallaire** [comment]
That's unfortunate :-( I'll clean this up in the next release.
