### ISSUE TITLE
Cross-reference between articles on a website

### ISSUE THREAD

**Issue by joshpk** [rstudio/distill#245]
Hello, 
Is it possible to cross-reference between articles on a distill website? Within an article one can cross-reference sections using ids on a section header {#id} with the [linktosection] (#id) format. I would like to be able to do the same but linking between articles on the same webpage but have not been able to get that to work. Any direction would be much appreciated - thanks.

**Comment by jjallaire** [comment]
Unfortunately this isn't currently possible using the `\@ref` syntax. You could however do a view-source on the page you want to link to, find out the underlying `#hash` URL fragment, and then construct a link manually.
