### ISSUE TITLE
Typo - visa-vi should be vis-à-vis

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/distill#247]
This line writes _visa-vi_ which I'm assuming is to be read as _vis-à-vis_. 

https://github.com/rstudio/distill/blob/ceac0bb306fdc95bc8d5723fbb8a2b7c6ee35557/docs/website.Rmd#L98

**Comment by jjallaire** [comment]
Good catch, thanks! Just fixed.

**Comment by JosiahParry** [comment]
You're quick! Thanks JJ :)
