### ISSUE TITLE
Option to remove/hide title and header section of distill_article

### ISSUE THREAD

**Issue by mfherman** [rstudio/distill#257]
I've been really digging the updates to distill for generating websites -- thank you! I'm wondering if there is a YAML setting or a way to modify the CSS/HTML that would remove the entire header section (Title, Author, Date, etc.). I'm thinking this would be useful for a homepage of website, for example, where you don't necessarily want it.

Knitting with no title set in the YAML returns the following, with the R Markdown file name used as the title.

````
---
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

````
![image](https://user-images.githubusercontent.com/24945757/102915920-9d2d5b80-4450-11eb-8c6e-c9f2a3f9671f.png)

*First posted on [RStudio Community](https://community.rstudio.com/t/option-to-remove-hide-title-and-header-section-of-distill-article/90934)*

**Comment by jjallaire** [comment]
You could do something like this w/ CSS

`````
```{css}
d-title, d-byline {
  display: none
}
```
`````

**Comment by jjallaire** [comment]
Another approach would be that in the development version of distill you can have non-distill formats as pages in a distill site. So you could e.g have the homepage use `output: html_document` (w/ appropriate custom CSS, etc.) and do whatever you want there.

**Comment by mfherman** [comment]
Thank you! I think the css solution is simple enough for my use case. But the ability to include non-distill pages seems like a great option to explore in the future. Thanks!
