### ISSUE TITLE
Distill layout "l-body.side"

### ISSUE THREAD

**Issue by jeffwong** [rstudio/distill#263]
I see that distill layout options mostly follow layout section in the [original distill guide](https://distill.pub/guide/). Is it possible to use `layout="l-body.side"` as a chunk option? I've found that "l-body" works in R, but "l-body.side" does not scale the image to put it inline on the left of text.

Using Rstudio Version 1.3.1093 with distill 1.1

**Comment by jjallaire** [comment]
It appears as if that was a feature in distill v1 (https://github.com/distillpub/template/blob/v1/components/styles-layout.css) however we are using distill v2 which limits ".side" to just being an alias for `<aside>` (so it only goes in the gutter). This will work via `layout="l-body side"` (but again, it won't give you the behavior demonstrated in the distill guide as that's a v1 feature.

**Comment by cderv** [comment]
Duplicate of #95
