### ISSUE TITLE
Request for support for ISO/other date formats

### ISSUE THREAD

**Issue by RaoOfPhysics** [rstudio/distill#27]
Thanks for the nice package! Would you be willing to consider support for dates presented in a format other than `%B %d, %Y`, as mentioned in https://github.com/rstudio/radix/issues/23?

Perhaps entering the date with the ISO format of `YYYY-MM-DD` and allowing the user to select how it appears would be a good way forwards?

Many thanks, once again!

**Comment by jjallaire** [comment]
Yes, the tricky thing is that we'd need to try parsing the date a bunch of different ways. One further issue is that you really need to know in advance whether it's `MM-DD` or `DD-MM` (as otherwise you might transpose interpretation of days and months). As a result it's often better to require a specific format.

In terms of display output that's of course completely orthogonal so we could make that fix no matter what we do with input.

**Comment by jcolomb** [comment]
Hi,

I back up Rao on this, the format you ask for is not scientific, not inclusive (USA only), and it will bring interoperability problems (blogdown requires iso formated dates, for instance).

So if you can change it, please do !

**Comment by jjallaire** [comment]
@yihui What date format(s) do you parse from the `date` field in blogdown?

It looks like we already support parsing dates in ymd format via `lubridate::ymd`: https://github.com/rstudio/radix/blob/master/R/utils.R#L54-L63

In terms of display of dates, that's actually currently handled by Distill (the framework that Radix is based upon) but we could try to override what they are doing.

**Comment by yihui** [comment]
blogdown doesn't parse the date; Hugo does. Hugo's documentation didn't seem to say what kind of date formats are accepted, but it seems to favor ISO (either `2017-01-07T00:00:00Z` or `2017-01-07` is fine).

Given the endless pain with dealing with ambiguous date formats, personally I'd vote for ISO as the input format, too, and let users choose the display formats by themselves.

**Comment by jjallaire** [comment]
Okay, so as things currently stand we can parse ISO dates. However, date output is controlled by Distill and always of the form Jan. 7, 2017

**Comment by cderv** [comment]
I think this is now resolved and the date can be specified in the YAML field as YYYY-MM-DD.
