### ISSUE TITLE
Rendering markdown in blog post subtitle

### ISSUE THREAD

**Issue by shamindras** [rstudio/distill#271]
Thanks for making and developing the amazing `distill` package. 

One small issue I've found is that markdown does not render in the subtitle
(and possibly title) of `distill` blogposts. See this example below (from my blog):

<img width="906" alt="Screen Shot 2020-12-29 at 1 56 51 PM" src="https://user-images.githubusercontent.com/7627188/103307331-bf3d5580-49dd-11eb-8bdc-5346bd00ce92.png">

Here I expected the 'Tidyverse' (with backticks) to render as `Tidyverse` 
(code markdown). And similarly for `newcommand`

Now if you [open the post link](https://www.shamindras.com/posts/2019-08-21-shrotriya2019tidyfunpt2/), the markdown in the subtitle of the post
does indeed render correctly as follows:

<img width="710" alt="Screen Shot 2020-12-29 at 1 57 32 PM" src="https://user-images.githubusercontent.com/7627188/103307368-d67c4300-49dd-11eb-9f36-b7734205abe1.png">

I was wondering, if the markdown rendering could be fixed in the subititle card
of the main blogposts in `distill` as well?

**Comment by jjallaire** [comment]
We just added support for rendering the description as markdown within RSS feeds so it should be pretty easy to do what you are asking for as well. Will do this in the next release.

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/rstudio/distill/commit/6fe3097c3bf95c31196152cfba69edce3a3ef29b

**Comment by shamindras** [comment]
Thanks @jjallaire . When you say this is fixed, is the `distill` version 1.2
released on `CRAN`? Or do you mean fixed in the dev version of `distill`?

**Comment by jjallaire** [comment]
It's in the latest dev version.

**Comment by shamindras** [comment]
Thanks!

**Comment by jjallaire** [comment]
Unfortunately we had to revert support for rendering HTML within article descriptions: https://github.com/rstudio/distill/commit/6dfc29d4bd771d3fe65be19a2de0ebc396a15fe3

The listing page is completely munged if descriptions include links. This is happening somewhere within the Distill framework that we import, so there isn't really any way for us to resolve this right now (short of understanding the Distill framework better and getting a patch into it that resolves the issue).

**Comment by shamindras** [comment]
@jjallaire - I see, that's unfortunate. Thanks for letting me know. I've just re-installed the latest `dev` version and can confirm that this has reverted back to the original version first reported in this thread.

If you do resolve this at some point, please do let us know here.

**Comment by jjallaire** [comment]
Okay, will do!
