### ISSUE TITLE
rss file (index.xml) not being created

### ISSUE THREAD

**Issue by drfurtado** [rstudio/distill#274]
I have followed the steps to render the site but the "index.xml" file is not being created. 

Any help is greatly appreciated.

After "building" the site, the following message 

> Rendering: ./index.Rmd
> NOTE: Not creating feed for posts (no description provided) 

https://drfurtado.github.io/one11/
https://github.com/drfurtado/one11/blob/main/_site.yml

**Comment by shamindras** [comment]
@drfurtado - per the [RSS distill documentation](https://rstudio.github.io/distill/blog.html#rss-feed) it states that:

> Note that the description and base_url fields are both required to generate an RSS feed.

Based on the error message, I believe you may need to complete the `description` field and possibly the `base_url` field in the `_site.yml` file.

**Comment by drfurtado** [comment]
> @drfurtado - per the [RSS distill documentation](https://rstudio.github.io/distill/blog.html#rss-feed) it states that:
> 
> > Note that the description and base_url fields are both required to generate an RSS feed.
> 
> Based on the error message you have noted, I believe you may need to complete the `description` field and possibly the `base_url` field in the `_site.yml` file.
> 
> As an example here is what I have in the [description item](https://github.com/shamindras/ss_personal_distill_blog/blob/master/_site.yml#L3-L5) for my `distill` site.

Thank you! I missed that "detail".
