### ISSUE TITLE
Creating a Listing Page for a Collection in non-blog Distill website

### ISSUE THREAD

**Issue by howardm** [rstudio/distill#278]
Hi,

I'm creating a Distill website to serve as an online "textbook" with topic chapters. It currently has one "docs" folder (and one "images" folder) for the website content. It's version-controlled via Github.

I would like to create a page that would be the (aesthetic) equivalent of a Listing Page (example below) for a Distill blog that has the same format: an excerpt of the chapter introduction with a (preview) image alongside. I could manually update this page as I add and publish chapters.

I would have a navbar entry, something like Published Chapters, for this.

![Screen Shot 2021-01-01 at 11 32 41 AM](https://user-images.githubusercontent.com/6101226/103446750-5efa1e00-4c40-11eb-9553-def609f2c4f3.jpg)

I'd appreciate ideas about how I might achieve this.

Thanks.

Howard

**Comment by jjallaire** [comment]
You should be able to achieve this using a custom collection type: https://rstudio.github.io/distill/blog.html#collections. 

So you'd create a `chapters` collection. You could then also control the order of the listing page by explicitly enumerating the listing: https://rstudio.github.io/distill/blog.html#collections

**Comment by howardm** [comment]
O.K.

1. I didn't realize the following (from: https://alison.rbind.io/post/2020-12-22-postcards-distill/#add-a-blog):

"Add a blog

Back in your console, we can add a blog, using distill:

create_post("welcome")

If you do this with a blog already, it just adds a single post. But if you do this without posts set up, it does some nice things for you:

Creates a directory called _posts/ to hold all your future blog posts."

______

2. Then, if I create a new Collection directory "_analyses" how do I assign a new post -- using, say, "distill::create_post(title = "-------",  date_prefix = TRUE) -- to the _analyses directory rather than the _posts directory ? Stated differently, how do I create a new post in a particular directory when more than one exists ?

Thanks. 

Howard

**Comment by jjallaire** [comment]
You just create a new directory containing the Rmd file within the
_analyses directory (there is currently no wrapper function to do this).
You could I guess use create_post and then just move the post directory
over to _analyses.

**Comment by howardm** [comment]
O.K.  That'll work.

Thanks.

**Comment by cderv** [comment]
For reference, this has also been posted on the Community
https://community.rstudio.com/t/creating-a-listing-page-equivalent-in-a-distill-website
