### ISSUE TITLE
Listing page: Line break inserted before first link in YAML description field

### ISSUE THREAD

**Issue by julianbarg** [rstudio/distill#281]
I have just rebuilt my website after installing cc20d87 from Dec 31 via install_github. The article descriptions in the listing page are now knitted mostly correctly, but there is an issue where before the first link in every description, a line break is inserted. See screenshot below for example.

![Screenshot from 2021-01-03 10-11-47](https://user-images.githubusercontent.com/40502144/103481976-22e3cc00-4dac-11eb-88c2-16e2fcdf16d5.png)

Also, see https://www.jbarg.net/. Html file at https://github.com/julianbarg/jules_net/blob/main/docs/index.html for reference.

**Comment by jjallaire** [comment]
Unfortunately the resolution of this is to revert support for rendering HTML within article descriptions: https://github.com/rstudio/distill/commit/6dfc29d4bd771d3fe65be19a2de0ebc396a15fe3

The munging of the listing page is happening somewhere within the Distill framework that we import, so there isn't really any way for us to resolve this right now (short of understanding the Distill framework better and getting a patch into it that resolves the issue).
