### ISSUE TITLE
Listing page: Omitting affiliation in article YAML breaks formating

### ISSUE THREAD

**Issue by julianbarg** [rstudio/distill#282]
Currently, whether there is an affiliation listed in YAML affects the formatting of a blog entry on the listing page--even though the affiliation itself is not displayed on the listing page. Posts that have an affiliation have the date and author correctly displayed on the left of the description on the listing page. Those which do not have an affiliation have the date and author displayed above the description, separated by a newline character. See screenshot below for an example of both behaviors.

![Screenshot from 2021-01-03 10-30-54](https://user-images.githubusercontent.com/40502144/103482412-cd5cee80-4dae-11eb-9e7b-fd421336625b.png)

Of course there might be another explanation for this behavior. It's just my best guess because my listing page has two articles with affiliation that show up correctly, and ten without affiliation that do not show up correctly. 

See rendered listing page here: https://www.jbarg.net/ . 

Html here: https://github.com/julianbarg/jules_net/blob/main/docs/index.html . 

Rmd for incorrectly rendered listing here: https://github.com/julianbarg/jules_net/blob/main/_posts/2020-12-18-ontology/ontology.Rmd . 

Rmd for correctly rendered listing here: https://github.com/julianbarg/jules_net/blob/main/_posts/2020-12-17-new-school-of-environmental-economics/new-school-of-environmental-economics.Rmd

**Comment by jjallaire** [comment]
I believe this issue was caused by the rendering of a link within the description field (which caused Distill to munge the listing in a way that we don't currently understand). I reverted support for rendering HTML within the description here: https://github.com/rstudio/distill/commit/6dfc29d4bd771d3fe65be19a2de0ebc396a15fe3. This should resolve this issue as well.
