### ISSUE TITLE
Ability to change name of "posts" folder in "_site" dir?

### ISSUE THREAD

**Issue by werkstattcodes** [rstudio/distill#284]
I am moving my blog from blogdown to distill (like many others). One thing which bothers me though is that my blogdown posts are available via mysite.com/post/blog1/ while those on the new distill site are under mysite.com/postS/blog1/. Due the difference post vs posts any links which were previously shared get broken. Hence, the question whether there is a possibility to change the name of the destination folder.  
I would think that this issue affects everyone moving from blogdown to distill.
Many thanks.

**Comment by jjallaire** [comment]
There is actually nothing special about "_posts" in Distill (you can name collections of articles anything you like). So if you rename the folder `_post` and change your listing YAML to `listing: post` then it should work as you expect.

I guess the one thing that is "special" about posts is the `create_post()` function which targets the `_posts` directory but we could certainly add a parameters there to enable it to target any collection.

**Comment by werkstattcodes** [comment]
Many thanks for the quick reply. Just tried it out and works as suggested. Adding a parameter to the `create_post() `function would be indeed helpful.

**Comment by werkstattcodes** [comment]
Update: When changing the directory's name (e.g. `_post `instead of `_posts`), the search function stops returning results for the blog posts (only hits on the about page and listing page are returned in my case).

**Comment by jjallaire** [comment]
Thanks for reporting this -- try again from master should.now be working as expected.

**Comment by jjallaire** [comment]
I've also added a `collection` parameter to the `create_post()` function.

**Comment by werkstattcodes** [comment]
Great. Can confirm - both works: able to define name of post(s) directory & search covers them. Many thanks!
