### ISSUE TITLE
Navbar differences when using postcards for about page

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/distill#288]
Hi,

I've been working on building out a `distill` blog and also using `postcards` for the "About" page. It seems to mostly work smoothly, however, the navbars are slightly different between the listings page (`index.html`) and the postcards + navbar page (`about.html`). I can't seem to figure out the issue. It's noticable if you flip back and forth between the "Posts" and "About" pages [here](https://mattwarkentin.github.io/). The code for this website is [here](https://github.com/mattwarkentin/mattwarkentin.github.io), if it's helpful.

Notably:
- The difference in navbar thickness
- Search bar display (text centering/size)
- Generally alignment (e.g. logo, title)

It _seems_ like there might be some issues with CSS inheritance that is causing the differences, but I haven't quite figured out the issue. I don't really know enough about what's going on behind the scenes in order to add the navbar to the postcard during site generation.

**Comment by jjallaire** [comment]
The problem is that since postcards uses bootstrap, a whole ton of additional CSS is injected into the page which we can't really control for. The resulting differences are pretty subtle, so I think it's tolerable for now.

**Comment by mattwarkentin** [comment]
Thanks for the response. I sort of figured something along those lines was going on. If I can hack together a solution I will report back with what I did - otherwise, as you say, it's tolerable for now.
