### ISSUE TITLE
remove unwanted "Articles" category

### ISSUE THREAD

**Issue by acastroaraujo** [rstudio/distill#296]
How can we remove the automatically created "Articles" category from the listing page in a distill blog?

As far as I can tell, it's redundant.

For example, on the [Reproducible Finance with R](https://beta.rstudioconnect.com/content/11424/) we have this:

<img width="1288" alt="Screen Shot 2021-01-18 at 3 44 38 PM" src="https://user-images.githubusercontent.com/7806658/104961438-53c72200-59a4-11eb-8f9f-9ede08a6c390.png">

The "Articles" category serves no purpose, it's just taking space, right?

Thank you (I love this package)

**Comment by jjallaire** [comment]
The purpose of "articles" is to provide a target that gives you posts from all categories (it's essentially "all", except "all" sounds a bit off as a category. You could get rid of it w/ CSS otherwise we'd need to add an option to prevent it.

**Comment by acastroaraujo** [comment]
Thank you.

In case anyone else out there is interested, this little snippet seems to work fine for this purpose:

```
.sidebar-section.categories > ul > li:first-child {
  display: none;
}
```
