### ISSUE TITLE
Change code background color

### ISSUE THREAD

**Issue by modche** [rstudio/distill#298]
Hello,
nice package!
Is there an easy way to change the background color of inline code snippets. I search for a possibility to have the same `background colour` as here or here: https://rmarkdown.rstudio.com/github_document_format.html.

Thanks.

**Comment by etiennebacher** [comment]
Hi, I did it with the following CSS rules:
```
d-article div.sourceCode pre {
  background: #dae7f1;
}

code {
  background-color: #dae7f1;
}

d-article pre  {
  background-color: #dae7f1;
}
```
(Some of these are maybe redundant but it works)
Replace `#dae7f1` with the color you want

**Comment by cderv** [comment]
Using CSS is a good way to customize the background color: https://rstudio.github.io/distill/website.html#custom-style
In **distill**, you can also customize the higlighting them: https://rstudio.github.io/distill/#syntax-highlighting

This should allow you to achieve the change in background color you are looking for. 

I'll close this but feel free to reach out if this is not working as expected.
