### ISSUE TITLE
Text output wider than html margin

### ISSUE THREAD

**Issue by gabevar** [rstudio/distill#304]
Hi Distill team, thank you so much for the incredible work. My apologies if the answer to this question is obvious.

Some of the code output of an r-markdown distill article end up being pushed further than the bounds of browsers showing the code from html document. Here is an example screenshot:

<img width="1435" alt="Screen Shot 2021-01-29 at 6 54 33 PM" src="https://user-images.githubusercontent.com/39100648/106345223-78a07c80-6263-11eb-822d-5d72c9413ef7.png">

This seems to be occurring only for code chunks and not for regular text. Am I missing some key set of distill attributes?

Thank you.

**Comment by jjallaire** [comment]
Yes, code chunks are allowed to overflow the margin b/c code is often wider than the main body column (which covers in the neighborhood of 80 characters). We used to clip the code (and show a horizontal scrollbar) but users hated that b/c it obscured code that there was clearly room to show (in the large right margin)

**Comment by gabevar** [comment]
That makes complete sense, thank you for the quick answer.
