### ISSUE TITLE
Speed comparision blogdown (hugo) vs distill

### ISSUE THREAD

**Issue by werkstattcodes** [rstudio/distill#321]
I moved my blog from blogdown to distill. Now, I notice that the page is considerable slower than previously. This is the first time that I am dealing with such an issue and lack any prior knowledge, but a simple comparison via google’s pagespeed service result in 57 (mobile)/82 (desktop) in contrast to blogdown’s 88 (mobile) / 97 (desktop).

You can compare the two (almost identical) versions of the blog here:
https://developers.google.com/speed/pagespeed/insights/?url=werk.statt.codes
https://developers.google.com/speed/pagespeed/insights/?url=werkstatt-draft.netlify.app

Is this because blogdown is written in hugo and therefore simply faster? Is this something distill user’s have simply to live with. Or can I change something in how I setup my distill blog?

Many thanks!

**Comment by jjallaire** [comment]
That has to do with the particular JS and CSS libraries in play in the respective sites (nothing to do w/ Hugo per-se as that affects site build time not page load time). There is indeed nothing you can change on your end to address this.
