### ISSUE TITLE
full content in RSS feeds

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/distill#33]
Currently, the RSS feeds only contain title and description. I always find that annoying because it means I cannot preload blog posts to read offline in my feed reader. Of course, much of the nice layout of radix would be lost, but still, would it be possible to make the RSS feed contain the entire content (as an option)?
Really loving it so far by the way! Works very well out of the box, and easier than many alternatives I tried before.

**Comment by jjallaire** [comment]
We currently don't do this for exactly the reason you speculate: layout and interactive components (e.g. htmlwidgets) would be entirely lost. It's not out of the question, we'd probably just need to do second pass over the .md file created via `knit()` and render a more vanilla html version.

**Comment by rubenarslan** [comment]
I'd still like such a stripped down version, and I think I might not be alone in this, but I don't really know how many people still use feed readers in the way I describe. And at least in my previous attempts, my interactive graphs made in R usually didn't translate that well to mobile anyway, so not that much was lost. But maybe that's just by inferior htmlwidget skillz

**Comment by knapply** [comment]
Something to consider if it hasn’t been already: There are a lot of R-users that still rely on R-bloggers for any R-related content (Facebook and email list-only social media folks). For a blog to be added to their list, it needs to provide full RSS. https://www.r-bloggers.com/add-your-blog/page/5/

**Comment by jjallaire** [comment]
Yes, I agree that's the biggest shortcoming of not doing full RSS feeds. In order to do full content we would need to do a second render pass which generates HTML that uses screenshots for any JavaScript content. This is a bit tricky (and possibly exacts a material time penalty on all renders) so we haven't explored this yet.
