### ISSUE TITLE
Include R code in site footer

### ISSUE THREAD

**Issue by jhelvy** [rstudio/distill#334]
This is more of a feature request, but does anyone know how to include R code in the site footer?

I want to add a line like this to note when the site was last updated:

```html
<span style="font-size:0.8rem;">Last updated on `r format(Sys.Date(), format="%B %d %Y")`</span>
```

But if I put this in the `_footer.html` file the r code won't compile since it's in an html file that doesn't get rendered during the site build process.

**Comment by etiennebacher** [comment]
One solution is to create a custom function to generate this particular line in `_footer.html`. For example, you could create something like:
```
create_footer <- function() {
  
  ### Create HTML for footer
  footer_date <- as.character(shiny::tags$span(
    style="font-size:0.8rem;",
    paste0("Last updated on ", format(Sys.Date(), format="%B %d %Y"))
  ))
  
  ### Remove the line with "Last updated on..." if it exists
  ### to avoid a duplicated line
  orig_file <- readLines("_footer.html", warn = F)
  orig_file[which(grepl("Last updated on", orig_file))] <- ""
  
  ### Add the line "Last updated on..."
  new_file <- orig_file
  new_file[length(new_file) + 1] <- footer_date
  
  ### Overwrite the existing file
  cat(paste(new_file, collapse = "\n"), file = "_footer.html")
}

create_footer()
```
To run this function automatically when you build the site, you could include:
```
source("create_footer.R")
```
in a `.Rmd` file that already exists.

**Comment by jhelvy** [comment]
Yeah I thought about this, but it has to build the footer before it builds any other pages. If I call `create_footer()` inside, say, `index.Rmd`,  it won't get built in time. I would have to render the site twice - first time it creates `_footer.html`, second time it gets included in the build. 

What I need is a way to call `create_footer()` at the top of the build process rather than inside a .Rmd file.

**Comment by etiennebacher** [comment]
Going further into the customization, you could create your own function that calls `create_footer()` first and then `rmarkdown::render_site()` (which is called to build the site). However, I'm not sure this custom function can be called with the shortcuts or the buttons in RStudio.

**Comment by jhelvy** [comment]
That worked!

I make a file called [`build_site.R`](https://github.com/jhelvy/jhelvy.github.io/blob/master/build_site.R) that loads my [`functions.R`](https://github.com/jhelvy/jhelvy.github.io/blob/master/R/functions.R) file, which contains `create_footer()`, then calls `create_footer()` and then `rmarkdown::render_site(encoding = 'UTF-8')`. 

So I just need to run `build_site.R`, which is convenient since I can call it in my [github action](https://github.com/jhelvy/jhelvy.github.io/blob/master/.github/workflows/main.yml) workflow to build the site on each commit!
