### ISSUE TITLE
No citation hover for multiple works

### ISSUE THREAD

**Issue by tgoldring** [rstudio/distill#335]
When I create a single citation, the hover functionality works perfectly:  e.g., `[@xie2015]`

![screenshot1](https://user-images.githubusercontent.com/41700546/110250980-537ee800-7f4c-11eb-82b1-962809576014.png)

If I add multiple citations separated by a semicolon, the hover box for both citations is empty. However, both citations correctly link to their references at the end of the article: e.g., `[@xie2015; @xie2015]`.

![screenshot2](https://user-images.githubusercontent.com/41700546/110250991-609bd700-7f4c-11eb-8f0c-3c375b44cad8.png)

Is the blank hover box for multiple citations an issue or intentional behavior? Or am I doing something wrong?

Thank you!

**Comment by jjallaire** [comment]
Thanks for the report! Should be fixed here: https://github.com/rstudio/distill/commit/5beb7860d56530f7cbdda052c97c1357a94058a0
