### ISSUE TITLE
Twitter cards aren't built for {postcards} pages

### ISSUE THREAD

**Issue by jhelvy** [rstudio/distill#342]
I realize this is probably an issue with the {postcards} package, but it looks like the preview images are ignored on postcard pages, which is unfortunate since they're often used as the home page for sites. 

For example, my [home page](https://jhelvy.github.io/) uses a postcards layout and the source doesn't have twitter cards, but my [About page](https://jhelvy.github.io/about.html) is a distill article and has them.

Was just curious if this is something that might be able to be handled in {distill}, otherwise it might have to be added to {postcards}.

**Comment by apreshill** [comment]
possible duplicate of #294

**Comment by jhelvy** [comment]
Yup, I'd say that's a dup! Closing this as it looks like it'll be addressed in v1.3. Thanks for the metathis suggestion!

**Comment by cderv** [comment]
Duplicate of #294
