### ISSUE TITLE
custom 404.md files are overwritten 

### ISSUE THREAD

**Issue by sbalci** [rstudio/distill#350]
Hi,
I use distill for [my site](https://github.com/sbalci/sbalci.github.io/)
I publish the page from `docs` folder.
I want to add `custom 404 page` for github page as [described here](https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site).
For it to work I have to put `404.md` file under `docs` folder.
But when I build the page the `docs` folder is overwritten completely and `404.md` file is removed. I tried to add `.gitignore` under `docs` folder, but it is overwritten also.
Is there a way to put this `404.md` file in main folder, so that it will be copied to docs folder when I rebuild the page?

**Comment by etiennebacher** [comment]
Hi, I add a similar issue with a `_redirects` file that I wanted to put in the `_site` folder (equivalent of your `docs` folder I think). One solution is to put your `404.md` at the top of your repo, and then use github actions to copy it inside the `docs` folder each time you build the site.

You can see my github actions for that [here](https://github.com/etiennebacher/personal_website_distill/blob/master/.github/workflows/main.yml) (I also use it to build the site automatically).

**Comment by sbalci** [comment]
Thank you @etiennebacher I was thinking to do same via cron jobs on computer. Your solution seems to work. I will use it.
distill copies html files to deployment folder, but it would be nice if it allowed us to select which to be added as well. 
Just as the opposite of `exclude`

```yaml
include: ["404.md", "_redirects"]
```

**Comment by sbalci** [comment]
Well `404.md` tries to render to 404.html So I have to remove that file also for github custom 404 file to function

**Comment by etiennebacher** [comment]
I was going to propose adding a line in the github action to remove the `404.html` that is produced, but I see that you already added that. I guess your problem is solved?

**Comment by sbalci** [comment]
Thank you. The problem is solved. For future reference the code is here: https://github.com/sbalci/sbalci.github.io/blob/master/.github/workflows/RenderDeploySite.yml#L28
