### ISSUE TITLE
render_site(): Cannot Open Connection

### ISSUE THREAD

**Issue by ayushnoori** [rstudio/distill#374]
Hi there,

I am running a simple Distill website with several `.Rmd` files in the root directory. However, when I try to run `render_site()` I often receive the following error: `Error in file(con, "w") : cannot open the connection`. This error occurs intermittently and is not immediately reproducible to me. The file `<my-file>` which produces the error (see below) is also not consistent:
```
7: In file(con, "w") :
  cannot open file '<my-file>': Invalid argument
```

My temporary solution has been to delete all the `.html` files generated by `render_site()` in the root directory and try re-running again. This works with varying degrees of success - sometimes the site will render appropriately, other times `render_site()` will throw the same error.

Would appreciate any advice/guidance. Thanks!

**Comment by ayushnoori** [comment]
Sure, will do and follow-up. Thanks.

**Comment by ayushnoori** [comment]
Hi @cderv, following up here. I am not using a network drive or online storage; I am running R 4.0.3 on a Windows 10 machine. My `R\win-library\4.0` directory is in my OneDrive folder, but that is synced locally. Here's the output of `traceback()`:

```
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") : cannot open file 'qPCR-analysis.html': Invalid argument
> traceback()
15: file(con, "w")
14: writeLines(enc2utf8(text), con, ..., useBytes = TRUE)
13: write_utf8(output_str, output_file)
12: base(metadata, input_file, output_file, ...)
11: output_format$post_processor(front_matter, input, output_file, 
        clean, !quiet)
10: rmarkdown::render(...)
9: withCallingHandlers(expr, message = function(c) if (inherits(c, 
       classes)) tryInvokeRestart("muffleMessage"))
8: suppressMessages(rmarkdown::render(...))
7: render_one(input = x, output_format = file_output_format, output_options = list(lib_dir = "site_libs", 
       self_contained = FALSE), envir = envir, quiet = quiet)
6: FUN(X[[i]], ...)
5: lapply(X = X, FUN = FUN, ...)
4: sapply(files, function(x) {
       render_one <- if (isTRUE(config$new_session)) {
           render_new_session
       }
       else {
           render_current_session
       }
       if (!quiet) 
           message("\nRendering: ", x)
       file_output_format <- output_format
       if (is.function(output_format_filter)) {
           file_output_format <- output_format_filter(x, output_format)
       }
       output <- render_one(input = x, output_format = file_output_format, 
           output_options = list(lib_dir = "site_libs", self_contained = FALSE), 
           envir = envir, quiet = quiet)
       outputs <<- c(outputs, output)
       sidecar_files_dir <- knitr_files_dir(output)
       files_dir_info <- file.info(sidecar_files_dir)
       if (isTRUE(files_dir_info$isdir)) 
           outputs <<- c(outputs, sidecar_files_dir)
   })
3: default$render(input_file, output_format, envir, quiet, encoding, 
       ...)
2: generator$render(input_file = input_file, output_format = output_format, 
       envir = envir, quiet = quiet)
1: render_site()
```

Thanks again!

**Comment by ayushnoori** [comment]
The directory housing my repository is also within a DropBox directory; however, this is again fully synced locally. Will try pausing syncing and see if it resolves the issue.

**Comment by cderv** [comment]
Thanks for the information. 
The errors happens at post processor step. So your Rmd should already be a HTML document, that will be post process. Unfortunatly this document is not found. 

I know of existing issue with Online Drive and syncing service so this could be related. It is not only something with rmarkdown and could be with other files (e.g https://stackoverflow.com/a/31323823/3436535)

I am waiting for your feedback on pausing the sync. 

You could also try to move the project to a local directory not sync and see if it works from there.

**Comment by ayushnoori** [comment]
OK, based on a preliminary test, pausing DropBox sync temporarily seems to prevent the error. So, I will close this issue; if it reoccurs, will follow up here. Hopefully this will be beneficial to any other DropBox or DropBox Enterprise users out there interested in using `distill`. Thanks so much for your guidance, Christophe! I appreciate it.
