### ISSUE TITLE
Footer doesn't allow plausible tracker

### ISSUE THREAD

**Issue by koaning** [rstudio/distill#377]
I've been using [plausible.io](https://plausible.io) for anonymised tracking of my blog. It's a great service, but they recently updated how they track data. You now have to add this tag; 

```
<script async defer data-domain="koaning.io" src="https://plausible.io/js/plausible.js"></script>
```

Unfortunately, if I try to add this in the `_footer.html`, I get an error.

```
Error in read_xml.character(file) : 
  Specification mandates value for attribute async [41]
```

I think the XML parser is perhaps a bit too strict here. It does work when I run:

```
<script data-domain="koaning.io" src="https://plausible.io/js/plausible.js"></script>
```

**Comment by cderv** [comment]
This is an issue thrown by `xml2::read_xml()`,  but `xml2::read_html()` works

``` r
tmp <- tempfile()
xfun::write_utf8(
  '<script async defer data-domain="koaning.io" src="https://plausible.io/js/plausible.js"></script>',
  tmp)
xml2::read_xml(tmp)
#> Error in read_xml.character(tmp): Specification mandates value for attribute async [41]
xml2::read_html(tmp)
#> {html_document}
#> <html>
#> [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
unlink(tmp)
```

Where are you passing this `_footer.html` file in **distill** ? 

Thanks.

**Comment by koaning** [comment]
I just followed the docs [here](https://rstudio.github.io/distill/website.html#site-footer). There's no setting configured in the `_site.yml`. I merely have the `_footer.html` file in the root. 

It should be said, this issue can be fixed by adding plausible to the header as described [here](https://github.com/rstudio/distill/issues/378) so it's not really a problem anymore. But the error message does feel a bit out of place.

**Comment by cderv** [comment]
> But the error message does feel a bit out of place.

I agree. 

Thanks for the details. That should help identify what happens.

**Comment by cderv** [comment]
@koaning Can you try the PR ? 

```r
remotes::install_github("rstudio/distill#379")
```

I believe this should fix the issue you found. It would be much appreciated if you could try it. 

Thanks!

**Comment by koaning** [comment]
It seems to fail unfortunately. 

```
> remotes::install_github("rstudio/distill#379")
Skipping install of 'distill' from a github remote, the SHA1 (a7fbfa72) has not changed since last install.
  Use `force = TRUE` to force installation
  
> rmarkdown::render_site()
...
Output created: _site/index.html

Processing posts:
  _posts/just-another-dangerous-situation 
Error in read_xml.character(file) : 
  Specification mandates value for attribute async [41]
In addition: Warning messages:
1: In png::readPNG(metadata_path) :
  libpng warning: iCCP: known incorrect sRGB profile
2: In normalizePath(path, winslash = winslash, mustWork = mustWork) :
  path[1]="readme.knit.md": No such file or directory
```

**Comment by cderv** [comment]
I did missed something in the PR. Not sure it is directly related but could you retry by reinstalling and re testing ? 

Also if it errors, can you share the error traceback by calling `traceback()` right after the error occured ? 

Thanks.
