### ISSUE TITLE
References do not format correctly

### ISSUE THREAD

**Issue by ayushnoori** [rstudio/distill#392]
Hi there,

I am attempting to use references in a Distill article, however, am encountering several formatting issues.

First, hovering over the first two references shows an empty tooltip:

![image](https://user-images.githubusercontent.com/43010710/125176066-78e36300-e185-11eb-8b5b-58baf23355ad.png)

In contrast to the final reference, which shows a complete reference when hovered over:

![image](https://user-images.githubusercontent.com/43010710/125176078-8e588d00-e185-11eb-8ade-f25cb88a5989.png)

Further, the reference section at the end of the article does not line break correctly:

![image](https://user-images.githubusercontent.com/43010710/125176097-a3cdb700-e185-11eb-8d75-c035b683d897.png)

I am currently using the [`nature-communications.csl`](https://www.zotero.org/styles/nature-communications) file from the Zotero Style repository, however, have also tried with the parent Nature and with the Springer Vancouver citation styles, to no avail.

My YAML header is as follows:

```
---
title: "About"
site: distill::distill_website
bibliography: my-bibliography.bib
csl: nature-communications.csl
output:
  distill::distill_article:
    toc: true
---
```

Thanks for your help!

**Comment by ayushnoori** [comment]
Here is the BibTex information. Changing the type of the first two records from `@article` to `@incollection` does not resolve the issue.
```
@article{schindelin_fiji_2012,
	title = {Fiji: {An} {Open}-{Source} {Platform} for {Biological}-{Image} {Analysis}},
	volume = {9},
	issn = {1548-7105},
	shorttitle = {Fiji},
	doi = {10.1038/nmeth.2019},
	language = {eng},
	number = {7},
	journal = {Nature Methods},
	author = {Schindelin, Johannes and Arganda-Carreras, Ignacio and Frise, Erwin and Kaynig, Verena and Longair, Mark and Pietzsch, Tobias and Preibisch, Stephan and Rueden, Curtis and Saalfeld, Stephan and Schmid, Benjamin and Tinevez, Jean-Yves and White, Daniel James and Hartenstein, Volker and Eliceiri, Kevin and Tomancak, Pavel and Cardona, Albert},
	month = jun,
	year = {2012},
	pmid = {22743772},
	pmcid = {PMC3855844},
	pages = {676--682},
}

@article{rueden_imagej2_2017,
	title = {{ImageJ2}: {ImageJ} for the next generation of scientific image data},
	volume = {18},
	issn = {1471-2105},
	shorttitle = {{ImageJ2}},
	url = {https://doi.org/10.1186/s12859-017-1934-z},
	doi = {10.1186/s12859-017-1934-z},
	number = {1},
	urldate = {2021-02-28},
	journal = {BMC Bioinformatics},
	author = {Rueden, Curtis T. and Schindelin, Johannes and Hiner, Mark C. and DeZonia, Barry E. and Walter, Alison E. and Arena, Ellen T. and Eliceiri, Kevin W.},
	month = nov,
	year = {2017},
	pages = {529},
}

@incollection{paszke_pytorch_2019,
	title = {{PyTorch}: {An} {Imperative} {Style}, {High}-{Performance} {Deep} {Learning} {Library}},
	url = {http://papers.neurips.cc/paper/9015-pytorch-an-imperative-style-high-performance-deep-learning-library.pdf},
	booktitle = {Advances in {Neural} {Information} {Processing} {Systems} 32},
	publisher = {Curran Associates, Inc.},
	author = {Paszke, Adam and Gross, Sam and Massa, Francisco and Lerer, Adam and Bradbury, James and Chanan, Gregory and Killeen, Trevor and Lin, Zeming and Gimelshein, Natalia and Antiga, Luca and Desmaison, Alban and Kopf, Andreas and Yang, Edward and DeVito, Zachary and Raison, Martin and Tejani, Alykhan and Chilamkurthy, Sasank and Steiner, Benoit and Fang, Lu and Bai, Junjie and Chintala, Soumith},
	editor = {Wallach, H. and Larochelle, H. and Beygelzimer, A. and Alché-Buc, F. d{\textbackslash}textquotesingle and Fox, E. and Garnett, R.},
	year = {2019},
	pages = {8024--8035},
}
```

**Comment by cderv** [comment]
Hi @ayushnoori, 

> Further, the reference section at the end of the article does not line break correctly:

About this, some CSS rules from Pandoc are missing and I will add them. 

> First, hovering over the first two references shows an empty tooltip:

I can't reproduce this will this document 
````markdown
---
title: "About"
bibliography: my-bibliography.bib
csl: https://www.zotero.org/styles/nature-communications
output:
  distill::distill_article:
    toc: true
---

See @schindelin_fiji_2012 and @rueden_imagej2_2017 before look at @paszke_pytorch_2019
````

All references are correctly put in the hover. Can you share an example doc that does not work for you ? 

Also, can you check you have last version of packages ? 
And can you share the pandoc version you are using ? `rmarkdown::pandoc_version()`

Thank you.

**Comment by ayushnoori** [comment]
Hi @cderv, thanks for investigating this. I think I figured part of it out. I realized that the first two references were in the same citation (formatted according to [this documentation](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)), i.e.:

```
ImageJ is an image analysis program [@schindelin_fiji_2012; @rueden_imagej2_2017]. PyTorch is a machine learning library [@paszke_pytorch_2019].
```
If I changed to the following, then the hover works as expected:
```
FIJI is ImageJ [@schindelin_fiji_2012]. ImageJ is an image analysis program [@rueden_imagej2_2017]. PyTorch is a machine learning library [@paszke_pytorch_2019].
```
When you place the two citations within the same bracket, although they receive different numbers as expected, they seem to share the same tooltip/hover? I am using `distill` version 1.2 and `pandoc` version 2.11.4. I can test with `distill` version 1.2.4.

**Comment by cderv** [comment]
The first example work ok for me: 
![image](https://user-images.githubusercontent.com/6791940/125261008-29c23d00-e301-11eb-85af-e6283bc2441b.png)

But I am using last Pandoc (2.14.0.3)

**Comment by ayushnoori** [comment]
Ok, I will update my Pandoc and report back.

**Comment by cderv** [comment]
I tried with `2.11.4` too but still can't reproduce using
````markdown
---
title: "About"
bibliography: my-bibliography.bib
csl: https://www.zotero.org/styles/nature-communications
output:
  distill::distill_article:
    toc: true
---

ImageJ is an image analysis program [@schindelin_fiji_2012; @rueden_imagej2_2017]. PyTorch is a machine learning library [@paszke_pytorch_2019].
````

I am using dev version of `distill` though. 

I let you try with both ? And also updating rmarkdown and knitr is best.

**Comment by ayushnoori** [comment]
Ok, installing the development version of `distill` (version 1.2.4 from GitHub) seems to fix the issue. Please see below:

![image](https://user-images.githubusercontent.com/43010710/125263314-c65fed00-e2b7-11eb-8564-fa80a0e896d7.png)

The only thing left now are the CSS rules from Pandoc. I will try https://github.com/rstudio/distill/pull/393. Thanks for your help!

**Comment by ayushnoori** [comment]
#393 fixes the issue. See:

![image](https://user-images.githubusercontent.com/43010710/125264485-c1e80400-e2b8-11eb-97d6-4e3996e2ae3f.png)

Thanks again!

**Comment by cderv** [comment]
Glad you were able to confirm ! 

Just so you know for next time, when a PR fixes an issue, we prefer to link both and close the issue only when the PR is merged.

Github has special links and keyword for that. :) 

Thanks for your quick reply to test everything. I'll merge the PR now. This will we available in dev version then.

**Comment by ayushnoori** [comment]
That makes sense. Thank you for letting me know!
