### ISSUE TITLE
The version check for rstudio fails under certain conditions

### ISSUE THREAD

**Issue by tarensanders** [rstudio/distill#400]
Specifically, if you try to render the file from a [`targets`](https://github.com/ropensci/targets) pipeline, you get the error

`Distill articles cannot be previewed in this version of RStudio.`

After investigating, it seems that the problem is this line: 
https://github.com/rstudio/distill/blob/33f858a0e56cd083d55d8ff8df2ed7eecd27372a/R/rstudio.R#L43

The environment variable "RSTUDIO_VERSION" does not exist in my version of RStudio (Windows; 1.4.1725). `targets` uses `callr`, so the rstudioapi is not available, but the "RSTUDIO" environment variable still exists. Since the "RSTUDIO_VERSION" does not exist, it uses the default value which fails the check. I cannot find in the RStudio docs if this variable is no longer set.

I can't think of how to make a reprex for this, but as a way to reproduce you can pull the [targets minimal example repo](https://github.com/wlandau/targets-minimal) and change the Rmd to use distill. Then call `targets::tar_make()`.

As a workaround (for anyone else who finds this), I posed a solution [here](https://stackoverflow.com/questions/68888905/cannot-render-distill-article-in-a-targets-pipeline/68991226#68991226), which is just to define the environment variable at the top of the Rmd file (e.g., `Sys.setenv("RSTUDIO_VERSION" = '1.4.1725')`).

**Comment by cderv** [comment]
Thanks for the report. 

It seems like the variable `RSTUDIO_VERSION` is indeed no more set. This is probably something due to recent change on version scheme. I'll check that with the IDE team to see how to fix this (here or there)

Thank you !

**Comment by cderv** [comment]
After quickly looking at the code of RStudio IDE, I may have misunderstood when this variable is set. It seems this we are setting this variable during a rendering inside the IDE: https://github.com/rstudio/rstudio/blob/28942d8313bc4c0fa323d3097007ca20bf8bb0ab/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L607

And this should work for you - can you share the result of this ? 

````markdown
---
title: "Untitled"
output: html_document
---

```{r}
Sys.getenv("RSTUDIO_VERSION")
```
````

This should output a value. 

So I'll look in the interaction between targets and the way we are fetching the version. The assumption is that `RSTUDIO` environment variable should be set only in a child process of the IDE. I understand that targets run callr and inheriting all the environment variable including the ones from RStudio IDE.

**Comment by cderv** [comment]
Here is my understanding of the issue: 

* `distill:::rstudio_version()` assumes that if `RSTUDIO` is set, then the rendering is run from within RStudio in a background session (i.e using Knit button). 
* RStudio IDE sets a `RSTUDIO_VERSION` variable for the background process, which **distill** will then use, as it assumes it is in the rendering mode. 
* However, `callr::r()` will pass the environment variable, so the code ran will also have this variable set.
``` r
callr::r(function(x) Sys.getenv("RSTUDIO"))
#> [1] "1"
```
but `RSTUDIO_VERSION` won't be set by anything so not exist. 

I don't know if we should try anything complicated to change how we detect the version, think if `RSTUDIO` env var should be unset when running in **callr**, or else. We can maybe just assume that if `RSTUDIO_VERSION` is not available, we just can't get the version, so it is a hind that we are not inside RStudio for preview. So we don't error. With target, the preview is not needed anyway. 🤔

**Comment by cderv** [comment]
Here is a minimal reprex: 

``` r
dir.create(tmp_dir <- tempfile())
owd <- setwd(tmp_dir)
distill::create_article("test.Rmd", edit = FALSE)
# work in R console
# rmarkdown::render("test.Rmd")

# Calling render in callr does not work
callr::r(function(x) rmarkdown::render("test.Rmd"))
#> Error: callr subprocess failed: Distill articles cannot be previewed in this version of RStudio.
#> Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/
setwd(owd)
unlink(tmp_dir, recursive = TRUE)
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by tarensanders** [comment]
> And this should work for you - can you share the result of this ?

Yes, you're right. That prints the correct version in the knitted output. I also didn't realise that it was set during render - that's why I thought it was missing (I was just running it in console).

> We can maybe just assume that if `RSTUDIO_VERSION` is not available, we just can't get the version, so it is a hind that we are not inside RStudio for preview. So we don't error. With target, the preview is not needed anyway. 🤔

Don't think you're talking to me, but FWIW I think that's a good solution 👌

**Comment by cderv** [comment]
> Don't think you're talking to me, but FWIW I think that's a good solution

Oh I am talking to you, and anyone else who wants to share thoughts! 

As you have a workaround, I'll just take time to dig a bit deeper to see if I am missing something else.

**Comment by cderv** [comment]
I made a change to the way we are detecting things. I believe this should work ok now even in **targets**.
