### ISSUE TITLE
toc_float not working?

### ISSUE THREAD

**Issue by sj-io** [rstudio/distill#420]
Hello! I recently started a distill blog and my articles each have a table of contents. According to [the docs](https://rstudio.github.io/distill/basics.html#table-of-contents), `toc_float` is supposed to be enabled by default but it wasn't working for me. I added `toc_float: true` and that didn't work either. 

```
---
title: "Post title"
description: |
  Article description.
date: 2021-11-02
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
bibliography: references.bib
---
```

Then I started looking around I realized `toc_float` wasn't working on any distill blogs I saw, including posts in [The Distillery](https://distillery.rbind.io/tips_and_tricks.html)-- even [posts](https://distillery.rbind.io/posts/2021-05-26-custom-syntax-highlighting-for-distill-part-2-creating-the-palette/) that specifically have 'toc_float' enabled ([post repo link](https://github.com/jhelvy/distillery/blob/main/_posts/2021-05-26-custom-syntax-highlighting-for-distill-part-2-creating-the-palette/custom-syntax-highlighting-for-distill-part-2-creating-the-palette.Rmd)). If 'toc_float' is supposed to be enabled in the [distill docs](https://rstudio.github.io/distill/), it's not working there for me either. 

FWIW I'm using Firefox, but I ran into the same problem with Safari (and I made sure I was viewing at >1000 px). Anyone else having this issue?

**Comment by cderv** [comment]
Doc says 
> The table of contents will automatically float to the left when the article is displayed at more than 1000px wide. 

Did you check on a wide screen ? 

From the link you posted,
https://distillery.rbind.io/posts/2021-05-26-custom-syntax-highlighting-for-distill-part-2-creating-the-palette/
 I correctly see a toc floating on the left
![image](https://user-images.githubusercontent.com/6791940/140042893-7cc942c4-5527-41bf-bd03-3eb37353de22.png)

I am using Firefox too.

**Comment by sj-io** [comment]
Ahh, maybe I misunderstood what toc_float does? I thought it would keep the toc static to the left while you scroll (like [this site](https://biodash.github.io/codeclub/07_rmarkdown/)), not just move it to the left. The toc is showing on the left but stays at the top while scrolling.

**Comment by cderv** [comment]
Oh I see. The floating toc on the side is new from https://github.com/rstudio/distill/issues/16. 

See comment https://github.com/rstudio/distill/issues/16#issuecomment-692207662

It explains why it is fixed. Mainly because compare to other formats (like bookdown, or rmdformat or html document, or else) **distill** has a specific layout that allows for spreading into the margin. It would be difficult to do so with a TOC on the side. 

There is #341 proposal for a way to possibly make it appear on hover or movement. You can follow the issue there. 

Thanks for opening an issue !
