### ISSUE TITLE
Support for note style in CSL - currently double citation is created on hover

### ISSUE THREAD

**Issue by sj-io** [rstudio/distill#423]
Hey y'all! I'm trying to use a custom CSL for some blog posts so citations render as footnote-style instead of author-date format. I downloaded the [Chicago Manual of Style 17th edition (note, with Ibid.)](https://www.zotero.org/styles?q=id%3Achicago-note-bibliography-with-ibid) CSL file and added it to the folder for my post. When I began citing, distill automatically created a references.bib file to the folder. My YAML looks like:

```
---
title: "Post Title"
description: |
  Post description.
date: 2021-11-02
output:
  distill::distill_article:
    self_contained: false
csl: chicago-note-bibliography-with-ibid.csl
bibliography: references.bib
---
```

The citations format correctly in text, but on hover there are two pop-ups:

![Screen Shot 2021-11-02 at 10 11 35 PM](https://user-images.githubusercontent.com/57082282/140826080-b7799f63-1969-43d4-8003-1eeadaa285ac.png)

In other posts I used an earlier version of this CSL, the [Chicago Manual of Style 16th edition (full note)](https://www.zotero.org/styles?q=id%3Achicago-fullnote-bibliography-16th-edition), and had the same issue.

Thanks!

**Comment by cderv** [comment]
Thanks for the report and sorry for the delay. I believe this happens because Pandoc's handles directly CSL of note style citation
https://pandoc.org/MANUAL.html#citations-in-note-styles

As **distill** will use footnote style for all citation, it is processed twice currently. One of the processing should not be done. I'll see if we can deactivate the one in Pandoc, otherwise **distill** will have to adjust to this.

**Comment by cderv** [comment]
@sj-io can you try 
````r
remotes::install_github("rstudio/distill#440")
````

I have added a small JS tweak to only show on hover the **distill** usual reference tooltip. 

The reference in footnote should still be kept. 

Thanks for testing before I merge.

**Comment by sj-io** [comment]
It works! Thank you so much for getting to this. One small thing I noticed
is typically the footnotes will be hyperlink blue so they stand out, but
they're not in this version. It's not a big deal though, I'm just happy to
have the footnotes fixed.

[image: Screen Shot 2022-02-04 at 4.45.13 PM.png]

Thanks again!

**Comment by sj-io** [comment]
Sorry for the delay in response. So the color isn't hyperlink blue, but it is some bluish color that's definitely different from color of the main text. Still, I don't think it's a major issue and I'd consider my problem resolved. Thanks for all the help!
