### ISSUE TITLE
Add `aria-label` to links that use FA icons for accessibility

### ISSUE THREAD

**Issue by batpigandme** [rstudio/distill#424]
Hi squad,

In running my distill site through [WAVE](https://wave.webaim.org/) for accessibility checks, I've run into the "link-with-no-text" warning for the navigation/header links and the sharing links that use FontAwesome icons. We're doing the right thing (according to [the FA accessibility docs](https://wave.webaim.org/)) by using `aria-hidden` for the icons themselves, it's just that the link itself needs an `aria-label` for screen readers.

I got around this in the nav bar by using the "bug" in #151 (one man's bug, is another man's workaround), and I think this should be a pretty simple fix for the sharing links, since they already use names ("services") in the YAML. Pseudo-HTML would be something like: 

```html
<a href = sharing_link(service), aria-label=service>
<i class="fa fa-service" aria-hidden="true"></i>
</a>
```

https://github.com/rstudio/distill/blob/e53e8340afa386f638464899a66d22d083428b1f/R/collections.R#L672-L676

And it looks like it wouldn't be hard to plug into the existing code as it's set up right now.

Let me know if this sounds like it makes sense and/or if you want me to put a PR together.

Thanks,

Mara

**Comment by cderv** [comment]
Yes I think we can improve that. We do similar elsewhere 
https://github.com/rstudio/distill/blob/dcfab6615ddf2786ef56478cc04434a33c878d7f/R/navigation.R#L120-L125

So we should also do it in the code part you shared. We welcome a PR ! Thanks! 

And for reference, here is the link to FA accessibility that got lost in the post above https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/accessibility and example content

> (...) For instance, simply adding the aria-label attribute with a text description to the interactive element itself will be sufficient to provide an accessible alternative name for the element. (...)
> ```
> <a href="path/to/shopping/cart" aria-label="View 3 items in your shopping cart">
>  <i aria-hidden="true" class="fas fa-shopping-cart"></i>
> </a>
> ```

**Comment by batpigandme** [comment]
Great, thanks @cderv.
