### ISSUE TITLE
Support CC0 1.0 license

### ISSUE THREAD

**Issue by fkohrt** [rstudio/distill#431]
It would be nice if the [CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](http://creativecommons.org/publicdomain/zero/1.0/) would be supported as well for the `creative_commons` metadata key.

**Comment by cderv** [comment]
Currently only the licenses available at https://creativecommons.org/licenses/?lang=en are supported

https://github.com/rstudio/distill/blob/dcfab6615ddf2786ef56478cc04434a33c878d7f/R/metadata.R#L137-L145

For the one you suggest,  the URL is different so we would need a special handling 

https://github.com/rstudio/distill/blob/dcfab6615ddf2786ef56478cc04434a33c878d7f/R/metadata.R#L858-866

Is there a list of other licenses like CC0 we may need to add ? 

I believe CC0 is a special case right ? 
https://creativecommons.org/share-your-work/public-domain/cc0

Is there any other you know off ?

**Comment by fkohrt** [comment]
> Is there a list of other licenses like CC0 we may need to add ?

The CC 4.0 licenses and the CC0 1.0 are the ones available via Creative Commons' [License Chooser](https://chooser-beta.creativecommons.org/), so that should already cover most cases. CC also offers the [Public Domain Mark](http://creativecommons.org/publicdomain/mark/1.0/), but that is designed for indicating that something is already in the public domain, rather than for putting it into it.

Among [other licenses](https://www.gnu.org/licenses/license-list.en.html#OtherLicenses) the [GNU Free Documentation License](http://gnu.org/licenses/fdl-1.3.html) could be considered. I am not so sure about software licenses ([GPLv3](http://www.gnu.org/licenses/gpl-3.0.html), [AGPLv3](http://www.gnu.org/licenses/agpl-3.0.html), [LGPLv3](http://www.gnu.org/licenses/lgpl-3.0.html), [MIT](https://opensource.org/licenses/MIT), [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)). If you decide to add any, identifying them by their [SPDX License Identifiers](https://spdx.org/licenses/) would be nice, because they exist in multiple versions. (The same is true for CC licenses, [their license version matters](https://wiki.creativecommons.org/wiki/License_Versions).)

Also note that the canonical URIs for CC licenses linked via `rel` start with `http://`, not `https://`.

<details>
<summary>More info on canonical URIs</summary>

> All CC licenses have a canonical URI that starts with `http://`. It is used when describing the license status of works in a machine readable way and [the scheme is part of it](https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/). This can be verified when looking at the [RDF index of CC licenses](https://creativecommons.org/licenses/index.rdf) that contains all canonical URIs. See creativecommons/creativecommons.org#1030 and creativecommons/cc.licenserdf#7 for the relevant discussion at CC.
> 
> This is the same for the GNU licenses, which also have the `http` scheme as part of their canonical URI, see [gpl-3.0.rdf](https://www.gnu.org/licenses/gpl-3.0.rdf).
> 
> And it's also the same for the RightsStatements.org URIs, except (a) they display their canonical URIs [more prominently](https://pro.europeana.eu/page/available-rights-statements) in the first place and (b) the use of `http` is described in more detail in the [EDM Mapping Guidelines, section 4.2 + 4.3](https://pro.europeana.eu/page/edm-documentation).
> 
> Also, see IIIF/api#1874 if you are unsure about this, because the IIIF (Image Interoperability Framework) already had a discussion on this topic.

Source: https://github.com/h5p/h5p-editor-php-library/issues/124#issue-781809641
</details>

For CC 4.0 and CC0 1.0 licenses I have written a utility function, maybe it is of some use to you: https://gitlab.com/fkohrt/bachelorarbeit-code/-/blob/1fe83030/R/functions.R#L57-138

**Comment by cderv** [comment]
> The CC 4.0 licenses and the CC0 1.0 are the ones available via Creative Commons' License Chooser, so that should already cover most cases. 

So let's add the CC0. Do you want to make a PR for this tweaking the two places I shared above ? 
I don't know if we need to switch the helper completely.  Seems like adding a special handling for `creative_commons: CC0` will be enough. 

Regarding other licenses, we could bring support if needed but that would be another feature as not the same YAML key.

**Comment by fkohrt** [comment]
The text displayed in the appendix would need to change as well, as CC0 does not require attribution:

https://github.com/rstudio/distill/blob/dcfab6615ddf2786ef56478cc04434a33c878d7f/R/appendices.R#L89-L98

> So let's add the CC0. Do you want to make a PR for this tweaking the two places I shared above ? Otherwise I'll do it next time I work on distill

I don't have the capacities right now, so feel free to tackle this. Still, if find time, I will write a short note here.
