### ISSUE TITLE
Font sizes header 1 and 2 cannot be adjusted in css

### ISSUE THREAD

**Issue by carbonmetrics** [rstudio/distill#432]
I have created a style sheet with `create_theme`. 

There are all sorts of font sizes that can be adjusted, but not header 1 or header 2.
That's problematic, since H2 is larger than H1 in the current template.

How can I adjust font size for header 1 and 2 in the css file?

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)
distill 1.3
```

**Comment by cderv** [comment]
Hi, 

can you share an example of what you are trying to do ? What do you find to be missing in the theme file ? 

Using classic CSS rules should work to set font-size: 
For example: 
```css
d-article h2 {
  font-size: 30px;
}
```

this would be set in the custom css rule section https://rstudio.github.io/distill/website.html#custom-style

Also, about h1, **distill** works best when only h1 is the title of the article and the other header in the doc to be h2 or lower. 

Hope it helps

**Comment by carbonmetrics** [comment]
Thanks! This is what I was looking for.
What I was missing in the theme file was exactly the code snipped you included.

**Comment by cderv** [comment]
Ok great ! 

This is only CSS code. I would invite you to learn a bit about CSS and how to inspect a document in browser. There should be quite a handful number of resource online. This way you'll be able to create the theme you need for your website. 

I'll close this as it has been answered
