### ISSUE TITLE
Error rendering blog/listing HTML and tab on website, shows up blank when add new posts

### ISSUE THREAD

**Issue by esswhy** [rstudio/distill#447]
Hi! When I add a new blog post to my listing page named "Portfolio" for my `distill` website, I usually am able to see it and updated on my website after staging, committing, and pushing to [my website repo](https://github.com/esswhy/esswhy.github.io). 

<img width="960" alt="distill_render_listing_works" src="https://user-images.githubusercontent.com/13813359/159407836-5c8f917b-02fe-42d1-a0ff-7dd1c4bf708a.png">

However, I have noticed that when I try to add two or more posts at the same time/day, an error message like below shows up more often:

<img width="408" alt="distill_build_error" src="https://user-images.githubusercontent.com/13813359/159407875-e4d7cc2c-7d82-4b5e-925d-010071ebbc62.png">

Usually I just rebuild the website and it seems to work fine. 

When I add a new post, knitting the `.Rmd` file works and the `.html` file shows up fine. But then when I click on the "Portfolio" listing, it shows up blank. This is true for the `portfolio.html` file and when I go to [my website](https://esswhy.github.io/) on the tab. 

<img width="960" alt="distill_render_listing_error_blank" src="https://user-images.githubusercontent.com/13813359/159408171-a0434d22-4a09-4a49-92b2-56f04c4cf54f.png">

I notice that other `.html` files are not blank. have tried to create a new blog/listing with a new name and try to transfer the projects or posts there, but the issue would come up again. I've been having this issue occur repeatedly for the last 5 days and I am very confused why this is happening, or if it has something to do with the frequency in which I add new posts to the blog. 

Any feedback or direction to resolve this issue will be greatly appreciated.

**Comment by cderv** [comment]
Hi, 

thanks for the example live in your site. I can see in browser devtools window console this error 

![image](https://user-images.githubusercontent.com/6791940/159522370-101e9fa4-e87a-4cae-a23b-9d5643533acb.png)

This is something that should be fixed in version 1.3 of **distill** (by https://github.com/rstudio/distill/commit/0e374d6d81052efdff8fbd4ada124c4c5162c33b)

Can you check your **distill** version used for this website ? Using last CRAN version 1.3 should solve this. 

thanks!

**Comment by esswhy** [comment]
Hi @cderv , thank you for your response! I was using `distill` version 1.2 and just installed version 1.3 like you suggested. 
I was able to render the website and the Portfolio page exists now in both the preview and the online version of the website. Thank you so much for your help! Crossing my fingers that I won't have to run into this issue again :)
