### ISSUE TITLE
Feature request: Quarto notebooks

### ISSUE THREAD

**Issue by mihagazvoda** [rstudio/distill#453]
Hi!
Is there a way to use distill with Quarto? If so - how? If not, it would be great to be possible. 

Thank you.

Best,
Miha

**Comment by cderv** [comment]
Hi, 

I am not sure to understand correctly. What do you mean by using distill with Quarto ? What are you expecting ? 
Quarto has almost (if not all) features that **distill** offers. What are you missing ?

**Comment by mihagazvoda** [comment]
I'd like to write some Python Rmarkdown notebooks (without mini-conda installation). Just to create a separate virtual environment for the notebook and do the coding. Maybe I'm just not aware that this can be done with Rmarkdown, but it seems I need to use `reticulate` and mini-conda.

**Comment by cderv** [comment]
I'll try to give some additional information to help precise what you miss

* R can work with python using R 📦 **reticulate**. **It does not require a miniconda installation**. It will (should) work with any Python installation. I don't use miniconda myself on windows, only Python for Windows for python.org

* **reticulate** has a nice feature which a `python` engine for **knitr**. This is what allow a Rmd document to have `python` code chunk with nice feature like exchanging betwen R and python, or handling plots from python.  https://rstudio.github.io/reticulate/articles/r_markdown.html

* Quarto can work with an R **knitr** computation engine or a Python Jupyter computation engine. So for using with Python, it can either be used using R + **reticulate ** or direcly using Python no R required. 

So if you are interested in using Python only, you could directly use Quarto and build we website or blog with `.qmd` documents (and .Rmd document would work too). 

If you want to run Python with **distill**, you could just use **reticulate** with your python install - no need to change. 

Does that help ?

**Comment by mihagazvoda** [comment]
It helps, thank you very much!
