### ISSUE TITLE
Figure captions don't work for some text length with `(ref:...`

### ISSUE THREAD

**Issue by eliocamp** [rstudio/distill#463]
I'm having a very confusing issue trying to make the "(ref:caption)" syntax work. The code below is a reprex document that describes the issue. 

````
---
title: title
output: 
  distill::distill_article: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Caption works with a 50 character length caption 

(ref:caption1) `r paste0(rep("a", 50), collapse = "")`

```{r , fig.cap = "(ref:caption1)"}
plot(pressure)
```

But not with 51 characters

(ref:caption2) `r paste0(rep("a", 51), collapse = "")`

```{r , fig.cap = "(ref:caption2)"}
plot(pressure)
```


Remove one character from the ref name, and now it works with 51 characters. 


(ref:caption) `r paste0(rep("a", 51), collapse = "")`

```{r , fig.cap = "(ref:caption)"}
plot(pressure)
```


But add another chacater (total of 52 characters) to the caption, and it breaks again.

(ref:kaption) `r paste0(rep("a", 52), collapse = "")`

```{r , fig.cap = "(ref:kaption)"}
plot(pressure)
```


The limit seems to be the number of character in the name and in the caption. 

````
And here's the output: [test.html.zip](https://github.com/rstudio/distill/files/8818093/test.html.zip)

I'm using distill 1.4 and all other packages up-to-date with R 4.2.0

Infuriatingly, I cannot reproduce this behaviour on my institute server, which has R 3.6.3. But installing R 3.6.3 on my laptop does not fix it.

**Comment by cderv** [comment]
Thanks for the report. 

I was not aware this feature was suppose to work in **distill**. This is a **bookdown** feature, but it is indeed possible to use it within **distill** - I forgot. 

Anyway, this feature is implement using regex and I think it breaks because of the way the HTML is wrap by default with recent Pandoc version. This is also probably why you don't get the same results on your different environment: check the pandoc version there. 

I have pushed the same fix as we had in **bookdown** but that was not used by **distill**

**Comment by eliocamp** [comment]
Oh, thanks! 
Say, that autowrap thing also created some issues in rticles. If the template had a comment that had a template variable, then if the interpolation created a long string, the new line would not start with a comment and would create all sort of weird errors. 

So, for example, if the template has something like this:

```latex
% \title{$title$}
```

And ` title` was long, then the .tex file would be something like this

```latex
% \title{This is a very long title that pandoc will 
wrap into a new line}
```

and would fail. 

If you like, I could open an issue in the rticles repo about this.

**Comment by cderv** [comment]
> If you like, I could open an issue in the rticles repo about this.

Yes please do. 

I am thinking this should have been fixed at lower level in **rmarkdown** instead of in each format 🤔
