### ISSUE TITLE
Whether there are ways to support shiny_prerendered runtime?

### ISSUE THREAD

**Issue by hdeng88** [rstudio/distill#465]
I have successfully applied shiny_prerendered runtime on distill-articles. However, when it comes to the distill websites, it returns a blank page or is stuck on the home page. Any solutions?

**Comment by cderv** [comment]
Shiny prerendered is primarly design for Documentes. So it does not work correctly for website. 

This was asked in 
* https://community.rstudio.com/t/rmarkdown-website-using-shiny-prerendered-documents/29333/4
leading to this issue in 
* https://github.com/rstudio/rmarkdown/issues/1576

This is not a **distill** issue but a R Markdown limitation. I'll close this, and you can follow along this old issue. It is not something easy to solve as it probably require a redesign.
