### ISSUE TITLE
Distill article renders to empty page when an (unescaped) @ sign followed by characters is included in the text

### ISSUE THREAD

**Issue by L-Groeninger** [rstudio/distill#466]
Hello, I (may) have encountered an error that a `distill::distill_article` renders to empty/blank page when an @ sign followed by characters (e.g. `@xyz`) is included in the text. I use distill to maintain a blog and noticed that one article of mine where I had an unescaped @ sign in the text was just an empty/blank page. I suspect that this behaviour was introduced after I updated the distill package.

Here is a basic `distill::distill_article` that renders to an empty document when knitting it:

Example 1

``` r
---
title: "Untitled"
description: |
  A new article created using the Distill format.
date: "`r Sys.Date()`"
output: distill::distill_article
---

This distill article is rendered empty when including an @ sign followed by characters:

Example: @xyz
```

![distill_issue](https://user-images.githubusercontent.com/38919712/175960722-fea11130-9468-40fd-be18-8c728a4aad1e.png)

The following article however does knit properly when the @ sign is escaped by a backslash:

Example 2

``` r
---
title: "Untitled"
description: |
  A new article created using the Distill format.
date: "`r Sys.Date()`"
output: distill::distill_article
---

This distill article is rendered correctly when the @ sign has been escaped:

Example: \@xyz
```

![distill_issue_escaped](https://user-images.githubusercontent.com/38919712/175961162-059efb6f-198b-40e0-a110-e378b121751a.png)

Traditional RMarkdown Documents do not display this behaviour. Also interesting was that when I used `reprex::reprex_render("distill_test.Rmd")` the distill article of Example 1 with the unescaped @ sign was rendered properly.
I dont really know how, if it is an error or I just have to remember to escape special characters.
I didnt find a post/issue discussing this behaviour. Maybe there are peple who are affected as well.

I uninstalled distill version 1.4 and reinstalled distill version 1.3 and this behaviour disappeared. That means the documents then knitted properly even when there were unescaped @ signs in the text.

``` r
sessionInfo(package = "distill")
#> R version 4.2.0 (2022-04-22 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> character(0)
#> 
#> other attached packages:
#> [1] distill_1.4
#> 
#> loaded via a namespace (and not attached):
#>  [1] grDevices_4.2.0 digest_0.6.29   withr_2.5.0     magrittr_2.0.3 
#>  [5] reprex_2.0.1    evaluate_0.15   datasets_4.2.0  highr_0.9      
#>  [9] stringi_1.7.6   rlang_1.0.2     utils_4.2.0     cli_3.2.0      
#> [13] rstudioapi_0.13 fs_1.5.2        graphics_4.2.0  rmarkdown_2.14 
#> [17] base_4.2.0      tools_4.2.0     stringr_1.4.0   glue_1.6.2     
#> [21] xfun_0.30       yaml_2.3.5      fastmap_1.1.0   compiler_4.2.0 
#> [25] stats_4.2.0     htmltools_0.5.2 knitr_1.38      methods_4.2.0
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cderv** [comment]
Thanks for the report. This is coming from distill specific post processing in JS. 

By inserting `@xyz`, you are inserting a citation reference, but there is not bibliography file (more in https://rstudio.github.io/distill/citations.html). This will create in HTML 
```html
<span class="citation" data-cites="xyz">@xyz</span>
```
and post processing will consider it a citation. But it is not and we don't have a fallback for such issue. 

If this is not supposed to be a reference, then it should be escaped. `\@xyz` will be inserted as text in the HTML file. Hence no issue. 

I can add a specific handling on this so that JS does not error. But still, escaping should be used when `@` syntax is used because it is a specific character used for referencing (https://pandoc.org/MANUAL.html#extension-citations)

**Comment by L-Groeninger** [comment]
Thanks for the fast reply and the explanation!:)
Yes in my case of the blogpost it was not supposed to be a citation, but an example of an xpath. And when the Rmd Document rendered to a blank html page it threw no error that made investigating difficult. For the future I'll definitely remember to escape any special characters.

**Comment by cderv** [comment]
ok. I'll leave that open to consider improving it, at least the message.

**Comment by Lextuga007** [comment]
Just to say I've just encountered this when I had the @ in a name for example: `[@TwitterName](https://twitter.com/TwitterName)`. It's not necessary in the post I wrote but just in case it renders a blank page for anyone referring to something like a Twitter handle 🙂
