### ISSUE TITLE
Embed webpage within Distill blog.

### ISSUE THREAD

**Issue by RMRubert** [rstudio/distill#478]
Hello,

I wonder if it is possible to keep the top bar (menu logo), likely the bottom bar (if there is any) and in-between insert an external page. Like for example a contact-me form from netlify.

So far the only way I have found is with this code on a RMD file, that I placed at the bottom.

While this kind of works, it still keep the d-title section (Contact me form) and the iframe require me also to guess the height, which in this case it will not change, but for other cases it might,

My solution also creates a bug when you are knitting in Rstudio, and it opens like millions (more like 9) of new tabs in your default browser (at least on windows 10) pointing to that webpage, which it is annoying, but nothing terrible.

````markdown
---
title: "Contact me form"
description: |
date: 01-01-2023

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
knitr::include_url("https://contact.rmrubert.eu", height = "750px")
```
````

**Comment by cderv** [comment]
> My solution also creates a bug when you are knitting in Rstudio, and it opens like millions (more like 9) of new tabs in your default browser (at least on windows 10) pointing to that webpage, which it is annoying, but nothing terrible.

FWIW this is a known issue that should be solved soon https://github.com/rstudio/rstudio/issues/12494

> So far the only way I have found is with this code on a RMD file, that I placed at the bottom.

This seems like a good solution to me. What is the issue exactly ? Only the height to be set manually ?

**Comment by RMRubert** [comment]
I would like to get rid of the title iframe, in this case the Contact me form.

**Comment by cderv** [comment]
This is part of the default template of **distill**. 

So you can either 
* set an empty title in the YAML
* use some CSS to remove the node with `.d-title`. Example with CSS chunk
````markdown
```{css, echo = FALSE}
.d-title {
  display: none
}
```
````
or if you want to keep the title banner with delimiter
````markdown
```{css, echo = FALSE}
.d-title > h1 {
  display: none
}
```
````
* Use some JS to remove only the title text. Example with JS chunk 
````markdown
```{js, echo = FALSE}
window.addEventListener('DOMContentLoaded', (event) => {
    document.querySelector(".d-title > h1").innerText = ""
});
```
````

We don't have another way for now in a usual distill format. 

However, you can probably build something as **distill** supports any alternate format: https://rstudio.github.io/distill/website.html#alternate-formats
Example is the [postcard](https://github.com/seankross/postcards) format. It needs to be a tweak `html_document` as you want no theme and all. 

You need to have a clean format with probably a custom pandoc template as in Postcard. 
Something like 
```yaml
output: 
  html_document:
    theme: null
    math_method: null
    template: custom.html
```

I believe doing something like that would work. 

Hope it helps finding a workaround that suits you

**Comment by RMRubert** [comment]
This is very useful, thank you!
