### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by dicook** [rstudio/distill#480]
Hi @cderv This [issue ](https://github.com/rjournal/rjtools/issues/59#issue-1593767106) was posted on the rjtools site two weeks ago. Its not clear that we generally want to have subtitles but the news items for the journal, which is slightly different in format than a regular article, sometimes have subtitles.

**Comment by cderv** [comment]
Hi ! 

Sure I can look how to add subtitles and see where it should be placed in the distill template. Today we have `description` that will be place right under the title  (see [example source](https://github.com/rstudio/distill/blob/9c1a1a266b30fee175d0cbe5cfc7c3f2b7e0d283/docs/figures.Rmd#L3)  and [HTML](https://rstudio.github.io/distill/figures.html)

![image](https://user-images.githubusercontent.com/6791940/223096456-98f567eb-4fc2-4506-a620-d13720244ea0.png)

it is put as paragraph right below the title in the title block, but after categories and tag if any 

https://github.com/rstudio/distill/blob/9c1a1a266b30fee175d0cbe5cfc7c3f2b7e0d283/inst/rmarkdown/templates/distill_article/resources/default.html#L76-L88

In this part we also allow `description` to be not provided and in that case not included. 

However, it was tweaked by @mitchelloharawild in **rjtools** specifically to be an abstract: https://github.com/rjournal/rjtools/blob/8ff12f0f38355ea9249dffe119310c68ab8fa885/inst/rjdistill.html#L23

We need to see what should be done in **distill** and what in **rjtools**. 

Regarding format, how would the subtitle looks like ? I tried to see about "Changes on CRAN" I don't see one I think in https://journal.r-project.org/issues/2022-4/2022-4.pdf for example ? Is this the "by" in 
![image](https://user-images.githubusercontent.com/6791940/223097399-f1e591aa-f1e0-4a38-aef6-c103d5218ef5.png)

A paragraph of text just below the title, before any categories and tag ? 

I did a quick branch (#482) to add in template and this is a demo doc
```markdown
---
title: "Untitled"
subtitle: demo article
description: |
  A new article created using the Distill format.
categories:
  - portfolios
  - demo
author:
  - name: John Doe
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    keep_md: true
---

Content

````

We get this for no `subtitle` support: 
![image](https://user-images.githubusercontent.com/6791940/223102071-8d97404e-8b54-4127-9434-afc49632a64d.png)

and without categories
![image](https://user-images.githubusercontent.com/6791940/223102153-82d08f92-b7b4-4b2e-9466-20f31248ffc9.png)

Now with the branch
![image](https://user-images.githubusercontent.com/6791940/223102310-0aeb0cff-e2b1-490b-b020-4cf9dbef8f58.png)

and 
![image](https://user-images.githubusercontent.com/6791940/223102236-951b1c39-beaa-4cea-8a21-994865c3afc5.png)


Would that work for you ? Simple change on this side. 

--------------

On a side note, I believe from https://github.com/rjournal/rjtools/pull/58 that we should add also in **rticles** (https://github.com/rstudio/rticles/blob/main/inst/rmarkdown/templates/rjournal/resources/template.tex) 

We still have a R Journal template and format in **rticles** package - it seems like **rjtools** is replacing that. but that is another topic to discuss.

**Comment by zeileis** [comment]
The latest "Changes on CRAN" unfortunately does not have a subtitle because support wasn't added in time for the release of the issue. So the editors had to decide whether they prefer having a HTML version or the usual PDF with subtitle and no abstract. For the desired format see the PDF from a previous issue: https://journal.R-project.org/news/RJ-2022-3-cran/RJ-2022-3-cran.pdf

The subtitle is the date range: "2022-07-01 to 2022-10-31".

**Comment by dicook** [comment]
The subtitle format looks great @cderv

**Comment by zeileis** [comment]
Thanks for this, very much appreciated! :+1:
