### ISSUE TITLE
invalid byte sequence when deploying to github

### ISSUE THREAD

**Issue by cderv** [rstudio/distill#485]
Possibly related to #436

One example is below.  
https://github.com/Mihiretukebede/mihiretukebede.gitlub.io/blob/master/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/scraping-individual-participant-data-from-scatter-plots.Rmd

After knitting that rmd file and pushing the changes, the build page fails with the following error (only for this one but I have a hge chunk of such error for other files). 
```
Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/scraping-individual-participant-data-from-scatter-plots_files/figure-html5/unnamed-chunk-4-1.png: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/df.gif: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/paste-586399E8.png: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/scatterPlotdigitize.JPG: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/digitize.jpg: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/Animationnewlastr.gif: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/lm.png: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/publication.png: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/corr.png: invalid byte sequence in UTF-8
             Error: could not read file /github/workspace/_posts/2021-06-07-scraping-individual-participant-data-from-scatter-plots/points.gif: invalid byte sequence in UTF-8
```

_Originally posted by @Mihiretukebede in https://github.com/rstudio/distill/issues/436#issuecomment-1487636190_

**Comment by cderv** [comment]
@Mihiretukebede thanks for sharing more on this. I created a new issue to discuss as this is not directly the same as #436 

You are seeing the error when deploying to Github. One comment on that (possibly not related but importat): 

Your [build where you see the error](https://github.com/Mihiretukebede/mihiretukebede.gitlub.io/actions/runs/4547901344/jobs/8026459422#step:4:24) is using Jekyll to render the site. This is the default as explained in https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#static-site-generators
> If you publish your site from a source branch, GitHub Pages will use Jekyll to build your site by default. If you want to use a static site generator other than Jekyll, we recommend that you write a GitHub Actions to build and publish your site instead. Otherwise, disable the Jekyll build process by creating an empty file called .nojekyll in the root of your publishing source, then follow your static site generator's instructions to build your site locally.

With a **distill** rendered website, you don't want Jekyll. Our [documentation](https://rstudio.github.io/distill/publish_article.html#github-pages) mentions this `.nojekyll` file addition
> Create a file named .nojekyll in your repository (this is required to disable some processing of HTML files that GitHub does by default).

I don't know if this is related to the problem but it definitely could be. Are you expecting the site to be built with Jekyll ? 

Other comment :  `encoding: utf-8` is unused in `distill_article()`. you probably don't need it.


Regarding the error, I see 
```
Error: could not read file /github/workspace/_posts/2020-09-30-2020-09-30-plotting-model-coefficients-in-a-forest-plot/2020-09-30-plotting-model-coefficients-in-a-forest-plot_files/figure-html5/unnamed-chunk-9-1.png: invalid byte sequence in UTF-8
````

This image for example is from 3 years ago https://github.com/Mihiretukebede/mihiretukebede.gitlub.io/blob/master/_posts/2020-09-30-2020-09-30-plotting-model-coefficients-in-a-forest-plot/2020-09-30-plotting-model-coefficients-in-a-forest-plot_files/figure-html5/unnamed-chunk-9-1.png

So I don't think this is a change in **distill** recently that made Github be unable to read the image. 

#436 was about some string we read / write in **distill** - here is seems like a Github / Jekyll issue somehow.

**Comment by Mihiretukebede** [comment]
Thank you very very much @cderv. That was amazing! I first couldn't believe simply adding an empty .nojekyll file would solve everything. It worked automagically!!!

**Comment by cderv** [comment]
Glad it works. I was afraid we missed something, glad it is just a misunderstanding issue.

I'll close this. Thanks !
