### ISSUE TITLE
Warning due to deprecation of 'format' argument to 'as.character.POSIXlt()'

### ISSUE THREAD

**Issue by mbojan** [rstudio/distill#488]
The package gives a warning during rendering:

```
Warning message:
In as.character.POSIXt(as.POSIXlt(x), ...) :
  as.character(td, ..) no longer obeys a 'format' argument; use format(td, ..) ?
```

I traced it to 

https://github.com/rstudio/distill/blob/9553c1114ad00a618877e06cab49e93e27d24c41/R/utils.R#L115

I believe `as.character()` should be replaced with `format()`.

**Comment by tech2188** [comment]
is there a hot fix?

**Comment by cderv** [comment]
this should be now fixed in the Dev version. Will be on CRAN soon
