### ISSUE TITLE
Gallery outdated, remove Quarto pages

### ISSUE THREAD

**Issue by z3tt** [rstudio/distill#499]
Hi there, thanks for all the efforts on the distill packages! 

I just noticed that e.g. "Th MockUp Blog" which is featured as one of a few example pages in the [official gallery here](https://pkgs.rstudio.com/distill/articles/examples.html) is not actually a distill page aynmore but was rebuild as a Quarto page (and, unfortunately, I realized it way too late). 

It would be great if the examples feature only those webpages that actually can serve as distill examples so that the next person doesn't spend too much time not realizing it's a different framework.

**Comment by cderv** [comment]
Thanks a lot ! This should be updated shortly !
