### ISSUE TITLE
radix RMarkdown customizations for heading-size, text-justify, affiliation-width, aside and footnotes

### ISSUE THREAD

**Issue by jananiravi** [rstudio/distill#61]
Thanks for a fabulous RMarkdown theme `team-radix`!
### Theme customization questions
I have a related customization questions. I'd like to modify the following options:

1. the font size of headings
2. font size of code blocks/inline codes (took a look at related #19 but couldn't figure it out) 
3. justification of text (justify instead of left-align)
4. increase the width of affiliations OR can that only be adjusted with the total width? And for this should I increase the `tidy.opts width cutoff` or `R.options width`?
5. adjust height of `<aside>` notes. When used near headings, it usually renders way above the heading making it hard to make the association. Anyway to move it closer to the same eye-level/start-of-text level?
6. what adjustment must I make to make the footnote hover-friendly and/or clickable. I tried both the radix format with ^[text] and the regular RMarkdown format for sequential calling and text reference at the end, e.g., [^1]. In both cases, I do see a link to go back to the inline reference but no way to click/hover and access the footnote without scrolling to the bottom. Suggestions, please?

### reprex versions that don't entirely address my customizations above
[Here's a gist](https://gist.github.com/jananiravi/c89f81d709032a9a9d4e3a0fb1fa5162) of the attempted `css` customization. This worked for a regular rmarkdown file, but not entirely for the `radix` `rmarkdown`. Also, [here is another gist](https://gist.github.com/jananiravi/316c827e71f4ebfb77491f8a32b06778) with a redundant looking `knitr` setup chunk. I've tried various width options for question 4 with little luck. Please advise suggestions to modify both gists & address the customization Qs above. Also, if there are too many seemingly unrelated Qs, I could create separate issues for each of them. Thank you for your help!

**Comment by jjallaire** [comment]
Right now we don't have time to make all of these things customizable via R-level options. Note that Radix is an "opinionated" document format that isn't really about extensive customization of defaults so I'm not sure that this is something we'll add in the future.

As a result I think CSS is indeed the best way to go. As you've no doubt discovered the CSS isn't entirely trivial, and in some cases b/c of the way the Distill framework (which is the basis of the Radix format) does CSS it's not possible at all to change the defaults.

**Comment by jananiravi** [comment]
Thanks for the response, @jjallaire 👍 I will look into finding these solutions from the `css` side. If I do succeed to solve the other customizations, I will post my solutions here for others w/ similar concerns. 

In the meantime, do you have any quick suggestions/workarounds for any of the Qs above, esp. pointers on how I can get Q2 (code chunk widths) and Q6 (hover over footnotes) to work since these are current inherent features of radix? Thanks again!

**Comment by jjallaire** [comment]
We set the R width option to 70 here: https://github.com/rstudio/radix/blob/master/R/radix_article.R#L69

You can override either globally or per-chunk via the `R.options` knitr chunk option. That said, it's not possible to override the font size on code chunks (because of the way Distill handles CSS for pre/code) so there is very little incentive to change this option, which is well tweaked for the Distill default font sizes.

I'll look into the footnote issue separately.

**Comment by jjallaire** [comment]
The footnote issue I can see with recent versions of Chrome however footnotes seem to work fine in older versions of Chrome, Firefox, and Safari. I've filed an issue upstream w/ Distill here: https://github.com/distillpub/template/issues/95

**Comment by apreshill** [comment]
@jananiravi we now have a distill theming system; docs are here ✨ 

https://rstudio.github.io/distill/website.html#theming

**Comment by jananiravi** [comment]
Thank you, @apreshill!
