### ISSUE TITLE
Why email address within all the posts in the following form?

### ISSUE THREAD

**Issue by henry090** [rstudio/distill#64]
Hi @jjallaire , When I am on the main page of my blog, my email address on the top of a page in the following form: **mailto:mymail@gmail.com**. But when I open any post on my blog, the mail address on the top of the page will be like  **site_address/mailto:mymail@gmail.com**. Why?

**Comment by jjallaire** [comment]
I think I know why but to know for sure and allow me to reproduce what you are seeing and verify the fix could you provide me with the exact code/yaml you are using here?

**Comment by henry090** [comment]
Email part is the same

<img width="412" alt="screen shot 2018-11-20 at 01 03 10" src="https://user-images.githubusercontent.com/38523699/48734848-206f9800-ec60-11e8-8b10-ef250ce0a375.png">

**Comment by jjallaire** [comment]
Okay, that's very helpful! Should be fixed here: https://github.com/rstudio/radix/commit/ee5190cce620501ac9b1358548afac148155f33a

**Comment by jjallaire** [comment]
I'm not seeing that locally. I think I'll need you to create a minimal reproducible example to debug further.

**Comment by henry090** [comment]
Well, I have just created a new blog and changed files within _site directory with previous ones and it works properly, now. Thank you :)
