### ISSUE TITLE
Preview picture will not be the same if you share them via sharing links

### ISSUE THREAD

**Issue by henry090** [rstudio/distill#66]
If you share some post via sharing links, the preview (while sharing on Facebook) picture **will not** be the same as it is in a preview picture on your site (post listing). A picture in sharing links becomes randomized and I do not know how to help you to reproduce that. BTW, it was working properly. 

Edit1: I have just noticed that while sharing on Facebook the link itself changes automatically a preview link... 
Edit 2: It works properly again. But could you explain why it (preview while sharing) begins working after 3-5 minutes?

**Comment by jjallaire** [comment]
We are providing metadata to Facebook (via open-graph) indicating what the preview image should be. Not sure why they were picking another image, maybe an intermittent bug?

**Comment by henry090** [comment]
Yes, maybe  
> an intermittent bug

Actually, when I loaded a new post, it did NOT change a preview image automatically and chose 1st gif image within post instead of preview in listing. Then I deleted post and created a copy. But this time the link stopped working --- **'404 not found'**. After 3-5 minutes it started working.
