### ISSUE TITLE
ship with all distill assets

### ISSUE THREAD

**Issue by maxheld83** [rstudio/distill#72]
this is beyond my js paygrade, but perhaps it would be possible to have radix produce output with *all* distill assets, and not have the distill js "call home", so as to avoid an external dependency and shenanigans as per #71?

**Comment by henry090** [comment]
It works now, I have tested it on Safari Desktop and Safari IOS.

**Comment by apreshill** [comment]
@maxheld83 can you please close if your issue is resolved? Thanks!

**Comment by maxheld83** [comment]
as I said, I'm not a frontend expert so I'm not too sure what best practices for shipping assets / using CDN etc are.
I raised this because #71 kind of spooked me.
But #71 hasn't happened again, and inspecting https://rstudio.github.io/distill/ in the browser reveals (AFAIK) no external, assets.
