### ISSUE TITLE
Suppress citations for a specific blogpost

### ISSUE THREAD

**Issue by shamindras** [rstudio/distill#75]
Hi All,

I've very recently setup a `radix` blog with the default `citations: true` in `_site.yml` so that a citation is created for every new blogpost. I've read the [citations section in detail](https://rstudio.github.io/radix/blog.html#citations) but still had the following queries:

1. How can I suppress the citation for a _specific blogpost_ i.e. what do I change in the specific blogposts' `yaml` to do this? 
2. Also will all blogposts with citations get automatically picked up by Google Scholar? I would not want this ideally but would want to manually add them to Google Scholar as required.

I like having the default citation behavior to be maintained and suppress the citations on a case by case basis for smaller blogposts. Hence these queries.

**Comment by jjallaire** [comment]
You can't (it's currently a setting that affects the entire collection of blog posts).

We also generate Google Scholar metadata tags automatically when your post is citeable.

**Comment by shamindras** [comment]
Thanks for clarifying - are there any plans to change this setting to allow specific blogposts to be non-citable? For example the Welcome post would fall in such a category.

Also, per your post:
> We also generate Google Scholar metadata tags automatically when your post is citeable.

Does this mean Google Scholar will automatically add cited post to your Google Scholar record? I am new to Google Scholar and would not want Welcome type posts to get cited. I hope my question makes sense.

**Comment by jjallaire** [comment]
I'm thinking that you don't to worry about this, because Google Scholar won't just automatically start indexing your blog (and in fact they don't as a general rule index blogs, it needs to be a proper online journal/publication). The fact that the metadata tags are there won't cause Google to include you, rather you need to explicitly apply / opt-in to that.

**Comment by shamindras** [comment]
Thanks @jjallaire 

So for clarifying and closing this issue I had the quick follow up queries (which others may have as well):

1. To clarify, the purpose of `radix` producing metadata tags for Google Scholar is so that **if** your blog becomes a recognized journal by Google Scholar (e.g. like [distill.pub](https://distill.pub/)) then the metadata tags will be used to pickup your citations automatically? Otherwise they are basically not used by any service is my understanding.
2. If I officially link my blog page to Google Scholar (which most researchers do) then Google Scholar won't pick up the blog posts since it is not a recognized journal which I have submitted for their consideration?
3. Are there any plans to manually remove citations for specific blogposts? I can appreciate that you are being consistent with the distill theme but may make sense for some smaller posts to override this. Just wanted to get your thoughts on this.

Thanks

**Comment by joftius** [comment]
I would also like the ability to specify which blog posts should include/suppress the citation information.

**Comment by jjallaire** [comment]
@shamindras Your understanding is indeed correct. 

I think it would be pretty easy to add support for `citation_metadata: false` for individual posts. I'll do that for the next release.

@shamindras and @joftius I'm curious what your motivation for suppressing the metadata is? (given that it's completely hidden from view for readers of your site).

**Comment by joftius** [comment]
The "Reuse" and "Citation" info does show visibly at the bottom of each blog post, e.g. I can see them here https://joshualoftus.com/posts/2020-11-23-least-squares-as-springs/

That makes sense for posts that people may want to cite, but I also sometimes post things that are just personal updates and would like to suppress the citation info then

**Comment by jjallaire** [comment]
Okay, that makes sense. Thanks!

**Comment by shamindras** [comment]
@jjallaire - my motivations for suppressing citations on some personal posts is the same as that noted by @joftius 

Also, a bigger concern was that if I link my personal (distill) themed page to google scholar, that it would pick up my blogpost metadata and start adding them automatically. I understand, based on your comments above that this is not going to be the case?
(Note I filed this issue a while back, so not sure what has changed in the distill backend since then)

**Comment by jjallaire** [comment]
Okay, thanks. Will make that change.

**Comment by jjallaire** [comment]
Addressed here: https://github.com/rstudio/distill/commit/899abfb700c23683164cb79139042987aec5b689

You can now at `citation: false` to an individual article to suppress inclusion of both Google Scholar metadata and the citation appendix.

**Comment by shamindras** [comment]
@jjallaire - thanks, just tested and it works well (using the latest dev version of `distill`). Appreciate your help.
