### ISSUE TITLE
Does "code_folding: hide" work for Radix?

### ISSUE THREAD

**Issue by henry090** [rstudio/distill#77]
**Hi,** 

```
The code_folding: hide option enables you to include R code but have it hidden by default. 
Users can then choose to show hidden R code chunks either individually or
 document-wide. 
```
```
---
title: "Habits"
output:
  html_document:
    code_folding: hide
---
```
**Is it possible to apply it to Radix based sites?**

**Comment by jjallaire** [comment]
No, this isn't currently a feature of Radix.

**Comment by ijlyttle** [comment]
Perhaps I could ask the follow-on question, would you consider it as a possible feature of this package?

**Comment by sidvenu** [comment]
@jjallaire just to bump this issue up, could you perhaps answer @ijlyttle 's question? Thanks for your time :)

**Comment by medewitt** [comment]
This is a a bit old bu @ijlyttle and @sidvenu I use this post-processing trick to add summary/ details around present code. I imagine it could be worked into some of the post-processing done by distill if there were interest:

```
distill_post_process <-function(in_html){
  
  in_distill <- xfun::read_utf8(in_html)
  
  out_distill <- gsub(pattern = '(<pre class="\\w+"><code>)', 
                      replacement = '<details> <summary>Show Code</summary>\\1', 
                      in_distill, perl = T)
  
  out_distill <- gsub(pattern = '(</code></pre>)', 
                      replacement = '</code></pre></details>', 
                      out_distill, perl = T)
  
  xfun::write_utf8(out_distill, in_html)
}
```

**Comment by jjallaire** [comment]
code folding has been implemented, docs here: https://rstudio.github.io/distill/#code-folding
