### ISSUE TITLE
Background colour for Code in Radix articles

### ISSUE THREAD

**Issue by modche** [rstudio/distill#79]
I like the `radix`-package. Is it possible to change the background colour of code snippets back to ne normal grey from the standard R Markdown, e.g. that way `y = a + bx`? Could I change this in CSS?

**Comment by modche** [comment]
So, I cannot find any solution on stackoverflow and the radix webpage says that suggestions for changes can be posted here.

**Comment by apreshill** [comment]
@modche  We now have a theming system and docs about how to change most colors ✨ 

https://rstudio.github.io/distill/website.html#theming

To change the background color for code, you'll still need to use custom CSS though.

https://rstudio.github.io/distill/website.html#custom-style
