### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by medewitt** [rstudio/distill#9]
Perhaps an enhancement could be to add support for a search feature via google or duckduck go that can be updated like the rss feed. This would add more general search capability past the tag filters.

Example: _search.html

```
> <form method="get" action="https://duckduckgo.com/">
> 	  <label for="search-field" class="show-for-sr">Search the site</label>
> 	  <input type="search" name="q" maxlength="255" placeholder="Search the site" id="search-field">
> 	  <input type="hidden" name="sites" value="https://my_website.com/"/>
> 	  <input type="hidden" name="k7" value="#faf8f8"/>
> 	  <input type="hidden" name="kj" value="#b33"/>
> 	  <input type="hidden" name="ky" value="#fafafa"/>
> 	  <input type="hidden" name="kx" value="b"/>
> 	  <input type="hidden" name="ko" value="-1"/>
> 	  <input type="hidden" name="k1" value="-1"/>
> 	  <input type="submit" value="DuckDuckGo Search" style="visibility: hidden;" />
> </form>

```
And then an update in the _siteconfig.yml

```
> `name: "Blog"
> title: "Michael DeWitt"
> description: |
>   Exploring the thoughts...
> output_dir: "docs"
> collections:
>   posts:
>     search: _search.html`
```

I imagine that I could tweak under the hood to get here, but it could be a nice potential option.

**Comment by jjallaire** [comment]
I would indeed like to add a search function but I was thinking I would locate the search box within the navigation bar (so it's always visible) and the make the actual backend mechanism extensible.

**Comment by epspi** [comment]
> I would indeed like to add a search function but I was thinking I would locate the search box within the navigation bar (so it's always visible) and the make the actual backend mechanism extensible.

Navbar search works well in [Knowledge Repo](https://github.com/airbnb/knowledge-repo/) and would look great here!
![image](https://user-images.githubusercontent.com/8306014/45885375-4a9dfa00-bd84-11e8-9375-3830b746396f.png)

**Comment by maxheld83** [comment]
[pkgdown](http://pkgdown.r-lib.org/articles/pkgdown.html) implements this via [docsearch](https://community.algolia.com/docsearch/), which works pretty well. 
Perhaps this could be reused here?
Might be familiar to rmarkdown users.

**Comment by aslm123** [comment]
You can use Google custom search engine service and attach the code to your about.rmd file and when you  build the site it renders a search bar. It can be an alternative until radix has its own search bar. 
https://www.google.com/cse/

**Comment by Opussci** [comment]
Is there any development regarding this issue?

**Comment by medewitt** [comment]
I ended up using lunr like what is done in the bookdown package, but I don't have the code converted to R (still in node, but it is an idea).

**Comment by jjallaire** [comment]
Closed via https://github.com/rstudio/distill/pull/164
