### ISSUE TITLE
Bug: Underscores in Nav Menu Change Link Names

### ISSUE THREAD

**Issue by phillc73** [rstudio/distill#91]
When using underscores in file names linked from a navigation menu, the html page links are altered, dropping everything after the underscore.

_site.yaml navigation looks like this in part:

```
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "Articles"
      href: articles_index.html
```
After the website is built, previewing in the RStudio Viewer pane and clicking on the relevant navigation bar link results in error:

```
/rmd_output/3/articles_./ not found
```
If the "Open in Browser" link is clicked and the website opens in a new Firefox tab, the link works and the correct `articles_index.html` file is loaded.

Initially, I thought everything was fine and the error was just somehow in the RStudio Viewer pane. However, when the website is deployed to Netlify, the error returns. In fact the file linked from the navigation menu is simply `websiteurl.com/articles_./`

I would link to the website, which is new and likely has zero traffic at the moment, but perhaps by the time you read this I will have fixed the error by renaming files without underscores!

If required, the website repository is at:

https://gitlab.com/phillc73/goodinplaces-website

**Comment by jjallaire** [comment]
The bug here isn't the underscore, it's the "index.html" (which we are doing a global search and replace for). So, for example if you changed the name of the page to articles.html or articles_listing.html then it would work fine. Will certainly fix the underlying bug but wanted you to also know what the workaround would be.

**Comment by phillc73** [comment]
Thanks @jjallaire for the details and explanation. At least I know not to call anything other pages `index`!

**Comment by cderv** [comment]
I have opened an issue in RStudio IDE for this. I believe the issue really there. 

I'll close this and we can all follow for a fix there. Thanks for the report

**Comment by cderv** [comment]
In fact it is indeed something coming from **distill**
https://github.com/rstudio/distill/blob/84e21e931cfbbcbebde5e31a78f6599139b5e7e6/inst/rmarkdown/templates/distill_article/resources/distill.html#L1304-L1309

Thanks @romainfrancois !
