### ISSUE TITLE
Typos in Creating a Blog (blog.Rmd)

### ISSUE THREAD

**Issue by jcblum** [rstudio/distill#94]
This first one affects documentation of `_site.yml` options:
https://github.com/rstudio/distill/blob/58c8865024afe2aa71b127c802a1abb753193d94/docs/blog.Rmd#L240

- ``pintrest`` should be ``pinterest``

The other two are just verb agreement problems:

https://github.com/rstudio/distill/blob/58c8865024afe2aa71b127c802a1abb753193d94/docs/blog.Rmd#L299

- `describe` should be `described`

https://github.com/rstudio/distill/blob/58c8865024afe2aa71b127c802a1abb753193d94/docs/blog.Rmd#L328

- `enable` should be `enables` (that is, assuming the authorial voice's idiolect has HTML as a noncount noun)

**Comment by jjallaire** [comment]
Thanks! Addressed all of those issues here: https://github.com/rstudio/distill/commit/35fbdef03181b1c51f9ea8308244d3f2514285a1
