### ISSUE TITLE
How to add footer to distill blog.

### ISSUE THREAD

**Issue by diwashrestha** [rstudio/distill#97]
I am trying to add footer to distill blog using the distill tutorial but it seems its not working. please provide the code to add in _site.yaml file.

**Comment by jbkunst** [comment]
Hi @sdiwash,

You *don't need* to add anything to the `_site.yaml`, you just need to create a `_footer.html` file in your proyect folder (https://github.com/jbkunst/blog/blob/master/_footer.html).

 Regards,

**Comment by sdiwash** [comment]
Thank you @jbkunst i created footer by creating the_footer. Html. I was using some html tags in the file that was giving error. But with your i added footer to my blog.

**Comment by apreshill** [comment]
Thanks for the question @diwashrestha and for the answer @jbkunst!
